const fs = require('fs');
const path = require('path');

const dataPath = path.join(__dirname, '../src/data/characters.json');
const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

// Mapping terjemahan kalimat contoh & kana kalimat utuh
const translations = {
  "秋は涼しいです。": { id: "Musim gugur itu sejuk.", kana: "あきはすずしいです。" },
  "毎朝コーヒーを飲みます。": { id: "Setiap pagi saya minum kopi.", kana: "まいあさコーヒーをのみます。" },
  "朝ご飯を食べましたか。": { id: "Apakah kamu sudah sarapan?", kana: "あさごはんをたべましたか。" },
  "明日は休みです。": { id: "Besok adalah hari libur.", kana: "あしたはやすみです。" },
  "公園で遊びます。": { id: "Bermain di taman.", kana: "こうえんであそびます。" },
  "今日は暖かいですね。": { id: "Hari ini hangat ya.", kana: "きょうはあたたかいですね。" },
  "頭が痛いです。": { id: "Kepala saya sakit.", kana: "あたまがいたいです。" },
  "新しい車を買いました。": { id: "Saya membeli mobil baru.", kana: "あたらしいくるまをかいました。" },
  "あちらへどうぞ。": { id: "Silakan ke sebelah sana.", kana: "あちらへどうぞ。" },
  "今日はとても暑いです。": { id: "Hari ini sangat panas.", kana: "きょうはとてもあついです。" },
  "お茶が熱いです。": { id: "Teh ini panas.", kana: "おちゃがあついです。" },
  "この本は厚いです。": { id: "Buku ini tebal.", kana: "このほんはあついです。" },
  "後で電話します。": { id: "Nanti saya telepon.", kana: "あとででんわします。" },
  "兄は会社員です。": { id: "Kakak laki-laki saya adalah pegawai perusahaan.", kana: "あにはかいしゃいんです。" },
  "姉は大学生です。": { id: "Kakak perempuan saya adalah mahasiswi.", kana: "あねはだいがくせいです。" },
  "アパートに住んでいます。": { id: "Saya tinggal di apartemen.", kana: "アパートにすんでいます。" },
  "シャワーを浴びます。": { id: "Saya mandi (menggunakan shower).", kana: "シャワーをあびます。" },
  "ここは危ないです。": { id: "Di sini berbahaya.", kana: "ここはあぶないです。" },
  "このケーキは甘いです。": { id: "Kue ini manis.", kana: "このケーキはあまいです。" },
  "あまり美味しくないです。": { id: "Tidak begitu enak.", kana: "あまりおいしくないです。" },
  "雨が降っています。": { id: "Hujan sedang turun.", kana: "あめがふっています。" },
  "手を洗います。": { id: "Mencuci tangan.", kana: "てをあらいます。" },
  "駅まで歩きます。": { id: "Saya berjalan kaki sampai stasiun.", kana: "えきまであるきます。" },
  "あれは私の鞄です。": { id: "Itu adalah tas saya.", kana: "あれはわたしのかばんです。" },
  "いい天気ですね。": { id: "Cuacanya bagus ya.", kana: "いいてんきですね。" },
  "いいえ、違います。": { id: "Bukan, itu salah.", kana: "いいえ、ちがいます。" },
  "彼は「はい」と言いました。": { id: "Dia berkata 'Iya'.", kana: "かれは「はい」といいました。" },
  "私の家は近いです。": { id: "Rumah saya dekat.", kana: "わたしのいえはちかいです。" },
  "学校に行きます。": { id: "Saya pergi ke sekolah.", kana: "がっこうにいきます。" },
  "りんごはいくつありますか。": { id: "Ada berapa banyak apel?", kana: "りんごはいくつありますか。" },
  "これはいくらですか。": { id: "Ini harganya berapa?", kana: "これはいくらですか。" },
  "池に魚がいます。": { id: "Ada ikan di kolam.", kana: "いけにさかながいます。" },
  "私は医者になりたいです。": { id: "Saya ingin menjadi dokter.", kana: "わたしはいしゃになりたいです。" },
  "椅子に座ってください。": { id: "Silakan duduk di kursi.", kana: "いすにすわってください。" },
  "今日は忙しいです。": { id: "Hari ini saya sibuk.", kana: "きょうはいそがしいです。" },
  "お腹が痛いです。": { id: "Perut saya sakit.", kana: "おなかがいたいです。" },
  "一番好きです。": { id: "Saya paling suka.", kana: "いちばんすきです。" },
  "一日中家にいました。": { id: "Saya berada di rumah sepanjang hari.", kana: "いちにちじゅういえにいました。" },
  "これが一番美味しいです。": { id: "Ini yang paling enak.", kana: "これがいちばんおいしいです。" },
  "誕生日はいつですか。": { id: "Kapan ulang tahunmu?", kana: "たんじょうびはいつですか。" },
  "みかんを五つ買いました。": { id: "Saya membeli lima buah jeruk.", kana: "みかんをいつつかいました。" },
  "いつもバスで学校に行きます。": { id: "Saya selalu pergi ke sekolah dengan bus.", kana: "いつもバスでがっこうにいきます。" },
  "犬が公園を走っています。": { id: "Anjing sedang berlari di taman.", kana: "いぬがこうえんをはしっています。" },
  "今は何時ですか。": { id: "Sekarang jam berapa?", kana: "いまはなんじですか。" },
  "この言葉の意味は何ですか。": { id: "Apa arti kata ini?", kana: "このことばのいみはなんですか。" },
  "妹は高校生です。": { id: "Adik perempuan saya adalah siswi SMA.", kana: "いもうとはこうこうせいです。" },
  "雨の日は嫌です。": { id: "Saya benci hari hujan.", kana: "あめのひはいやです。" },
  "入口で待っています。": { id: "Saya menunggu di pintu masuk.", kana: "いりぐちでまっています。" },
  "猫がいます。": { id: "Ada kucing.", kana: "ねこがいます。" },
  "お金が要ります。": { id: "Saya membutuhkan uang.", kana: "おかねがいります。" },
  "鞄に本を入れます。": { id: "Saya memasukkan buku ke dalam tas.", kana: "かばんにほんをいれます。" },
  "何色が好きですか。": { id: "Kamu suka warna apa?", kana: "なにいろがすきですか。" },
  "色々な物があります。": { id: "Ada bermacam-macam barang.", kana: "いろいろなものがあります。" },
  "机の上に本があります。": { id: "Ada buku di atas meja.", kana: "つくえのうえにほんがあります。" },
  "私の後ろに人がいます。": { id: "Ada orang di belakang saya.", kana: "わたしのうしろにひとがいます。" },
  "この紙は薄いです。": { id: "Kertas ini tipis.", kana: "このかみはうすいです。" },
  "日本の歌を歌います。": { id: "Saya menyanyikan lagu Jepang.", kana: "にほんのうたをうたいます。" },
  "カラオケで歌います。": { id: "Saya bernyanyi di karaoke.", kana: "カラオケでうたいます。" },
  "1990年に生まれました。": { id: "Saya lahir pada tahun 1990.", kana: "せんきゅうひゃくきゅうじゅうねんにうまれました。" },
  "海で泳ぎます。": { id: "Saya berenang di laut.", kana: "うみでおよぎます。" },
  "古い車を売ります。": { id: "Saya menjual mobil tua.", kana: "ふるいくるまをうります。" },
  "外が煩いです。": { id: "Di luar berisik.", kana: "そとがうるさいです。" },
  "上着を着ます。": { id: "Saya memakai jaket/jas.", kana: "うわぎをきます。" },
  "綺麗な絵ですね。": { id: "Gambar yang indah ya.", kana: "きれいなえですね。" },
  "週末に映画を見ます。": { id: "Saya menonton film di akhir pekan.", kana: "しゅうまつにえいがをみます。" },
  "映画館に行きます。": { id: "Saya pergi ke bioskop.", kana: "えいがかんに行きます。" },
  "英語が話せます。": { id: "Saya bisa berbicara bahasa Inggris.", kana: "えいごがはなせます。" },
  "ええ、そうです。": { id: "Iya, benar.", kana: "ええ、そうです。" },
  "駅で友達に会います。": { id: "Saya bertemu teman di stasiun.", kana: "えきでともだちにあいます。" },
  "エレベーターに乗ります。": { id: "Saya naik lift.", kana: "エレベーターにのります。" },
  "これは百円です。": { id: "Ini harganya seratus yen.", kana: "これはひゃくえんです。" },
  "鉛筆で書きます。": { id: "Saya menulis dengan pensil.", kana: "えんぴつでかきます。" },
  "お茶を飲みます。": { id: "Saya minum teh.", kana: "おちゃをのみます。" },
  "この寿司は美味しいです。": { id: "Sushi ini enak.", kana: "このすしはおいしいです。" },
  "人が多いです。": { id: "Orangnya banyak.", kana: "ひとがおおいです。" },
  "大きい家が欲しいです。": { id: "Saya ingin rumah yang besar.", kana: "おおきいいえがほしいです。" },
  "大きな声で話します。": { id: "Saya berbicara dengan suara keras.", kana: "おおきなこえではなします。" },
  "大勢の人がいます。": { id: "Ada banyak orang.", kana: "おおぜいのひとがいます。" },
  "お母さんは元気ですか。": { id: "Apakah ibumu sehat?", kana: "おかあさんはげんきですか。" },
  "お菓子を食べます。": { id: "Saya makan kue/snack.", kana: "おかしをたべます。" },
  "お金がありません。": { id: "Saya tidak punya uang.", kana: "おかねがありません。" },
  "毎朝六時に起きます。": { id: "Saya bangun jam 6 setiap pagi.", kana: "まいあさろくじにおきます。" },
  "ここに荷物を置きます。": { id: "Saya meletakkan barang di sini.", kana: "ここににもつをおきます。" },
  "奥さんに宜しく。": { id: "Salam untuk istrimu.", kana: "おくさんによろしく。" },
  "お酒を飲みません。": { id: "Saya tidak minum alkohol.", kana: "おさけをのみません。" },
  "お皿を洗います。": { id: "Saya mencuci piring.", kana: "おさらをあらいます。" },
  "伯父さんは東京に住んでいます。": { id: "Paman saya tinggal di Tokyo.", kana: "おじさんはとうきょうにすんでいます。" },
  "おじいさんは優しいです。": { id: "Kakek itu baik hati.", kana: "おじいさんはやさしいです。" },
  "日本語を教えてください。": { id: "Tolong ajarkan bahasa Jepang.", kana: "にほんごをおしえてください。" },
  "歩くのが遅いです。": { id: "Berjalannya lambat.", kana: "あるくのがおそいです。" },
  "お茶をどうぞ。": { id: "Silakan tehnya.", kana: "おちゃをどうぞ。" },
  "お手洗いはどこですか。": { id: "Toilet ada di mana?", kana: "おてあらいはどこですか。" },
  "お父さんは先生です。": { id: "Ayahmu adalah guru.", kana: "おとうさんはせんせいです。" },
  "弟は元気です。": { id: "Adik laki-laki saya sehat.", kana: "おとうとはげんきです。" },
  "男の人がいます。": { id: "Ada seorang laki-laki.", kana: "おとこのひとがいます。" },
  "男の子が走っています。": { id: "Anak laki-laki sedang berlari.", kana: "おとこのこがはしっています。" },
  "一昨日雨が降りました。": { id: "Kemarin lusa turun hujan.", kana: "おとといあめがふりました。" },
  "一昨年日本へ来ました。": { id: "Dua tahun lalu saya datang ke Jepang.", kana: "おととしにほんへきました。" },
  "大人の切符を買います。": { id: "Saya membeli tiket orang dewasa.", kana: "おとなのきっぷをかいます。" },
  "お腹が空きました。": { id: "Saya lapar.", kana: "おなかがすきました。" },
  "同じカバンを持っています。": { id: "Saya punya tas yang sama.", kana: "おなじカバンをもっています。" },
  "お兄さんは何歳ですか。": { id: "Berapa umur kakak laki-lakimu?", kana: "おにいさんはなんさいですか。" },
  "お姉さんは綺麗ですね。": { id: "Kakak perempuanmu cantik ya.", kana: "おねえさんはきれいですね。" },
  "伯母さんに会います。": { id: "Saya bertemu bibi.", kana: "おばさんにあいます。" },
  "おばあさんは元気です。": { id: "Nenek itu sehat.", kana: "おばあさんはげんきです。" },
  "お弁当を作ります。": { id: "Saya membuat bekal.", kana: "おべんとうをつくります。" },
  "漢字を覚えます。": { id: "Saya menghafal Kanji.", kana: "かんじをおぼえます。" },
  "この鞄は重いです。": { id: "Tas ini berat.", kana: "このかばんは重いです。" },
  "この映画は面白いです。": { id: "Film ini menarik.", kana: "このえいがはおもしろいです。" },
  "プールで泳ぎます。": { id: "Saya berenang di kolam renang.", kana: "プールでおよぎます。" },
  "電車を降ります。": { id: "Saya turun dari kereta.", kana: "でんしゃをおります。" },
  "仕事が終わりました。": { id: "Pekerjaannya sudah selesai.", kana: "しごとがおわりました。" },
  "音楽を聞きます。": { id: "Saya mendengarkan musik.", kana: "おんがくをききます。" },
  "女の人がいます。": { id: "Ada seorang perempuan.", kana: "おんなのひとがいます。" },
  "女の子が笑っています。": { id: "Anak perempuan sedang tersenyum.", kana: "おんなのこがわらっています。" },
  "外国へ行きたいです。": { id: "Saya ingin pergi ke luar negeri.", kana: "がいこくへいきたいです。" },
  "外国人の友達がいます。": { id: "Saya punya teman orang asing.", kana: "がいこくじんのともだちがいます。" },
  "会社で働きます。": { id: "Saya bekerja di perusahaan.", kana: "かいしゃではたらきます。" },
  "階段を上ります。": { id: "Saya naik tangga.", kana: "かいだんをのぼります。" },
  "スーパーへ買い物に行きます。": { id: "Saya pergi belanja ke supermarket.", kana: "スーパーへかいものにいきます。" },
  "新しい靴を買います。": { id: "Saya membeli sepatu baru.", kana: "あたらしいくつをかいます。" },
  "本を返します。": { id: "Saya mengembalikan buku.", kana: "ほんをかえします。" },
  "家に帰ります。": { id: "Saya pulang ke rumah.", kana: "いえにかえります。" },
  "顔を洗います。": { id: "Saya mencuci wajah.", kana: "かおをあらいます。" },
  "お金がかかります。": { id: "Membutuhkan uang.", kana: "おかねがかかります。" },
  "鍵をかけます。": { id: "Saya mengunci.", kana: "かぎをかけます。" },
  "手紙を書きます。": { id: "Saya menulis surat.", kana: "てがみをかきます。" },
  "私は学生です。": { id: "Saya adalah pelajar.", kana: "わたしはがくせいです。" },
  "傘をさします。": { id: "Saya menggunakan payung.", kana: "かさをさします。" },
  "ペンを貸してください。": { id: "Tolong pinjamkan pulpen.", kana: "ペンをかしてください。" },
  "風が強いです。": { id: "Anginnya kencang.", kana: "かぜがつよいです。" },
  "風邪をひきました。": { id: "Saya masuk angin/flu.", kana: "かぜをひきました。" },
  "家族は五人です。": { id: "Keluarga saya ada lima orang.", kana: "かぞくはごにんです。" },
  "あの方は誰ですか。": { id: "Beliau itu siapa?", kana: "あのかたはだれですか。" },
  "学校へ行きます。": { id: "Saya pergi ke sekolah.", kana: "がっこうへいきます。" },
  "カップでコーヒーを飲みます。": { id: "Saya minum kopi dengan cangkir.", kana: "カップでコーヒーをのみます。" },
  "家庭科を勉強します。": { id: "Saya belajar ilmu kesejahteraan keluarga.", kana: "かていかをべんきょうします。" },
  "その角を曲がってください。": { id: "Tolong belok di sudut itu.", kana: "そのかどをまがってください。" },
  "鞄に本を入れます。": { id: "Saya memasukkan buku ke dalam tas.", kana: "かばんにほんをいれます。" },
  "花瓶に花を飾ります。": { id: "Saya menghias bunga di vas.", kana: "かびんにはなをかざります。" },
  "紙に書きます。": { id: "Saya menulis di kertas.", kana: "かみにかきます。" },
  "カメラで写真を撮ります。": { id: "Saya memotret dengan kamera.", kana: "カメラでしゃしんをとります。" },
  "火曜日に会いましょう。": { id: "Mari bertemu di hari Selasa.", kana: "かようびにあいましょう。" },
  "このカレーは辛いです。": { id: "Kari ini pedas.", kana: "このカレーはからいです。" },
  "体にいいです。": { id: "Ini baik untuk tubuh.", kana: "からだにいいです。" },
  "本を借ります。": { id: "Saya meminjam buku.", kana: "ほんをかります。" },
  "この箱は軽いです。": { id: "Kotak ini ringan.", kana: "このはこはかるいです。" },
  "カレーを食べます。": { id: "Saya makan kari.", kana: "カレーをたべます。" },
  "カレンダーを見ます。": { id: "Saya melihat kalender.", kana: "カレンダーをみます。" },
  "川で泳ぎます。": { id: "Saya berenang di sungai.", kana: "かわでおよぎます。" },
  "可愛い猫ですね。": { id: "Kucing yang imut ya.", kana: "かわいいねこですね。" },
  "漢字は難しいです。": { id: "Kanji itu sulit.", kana: "かんじはむずかしいです。" },
  "大きな木があります。": { id: "Ada pohon yang besar.", kana: "おおきなきがあります。" },
  "黄色い花が咲いています。": { id: "Bunga kuning sedang mekar.", kana: "きいろいはながさいています。" },
  "電気が消えました。": { id: "Lampu telah padam.", kana: "でんきがきえました。" },
  "北へ行きます。": { id: "Saya pergi ke utara.", kana: "きたへいきます。" },
  "ギターを弾きます。": { id: "Saya bermain gitar.", kana: "ギターをひきます。" },
  "部屋が汚いです。": { id: "Kamarnya kotor.", kana: "へやがきたないです。" },
  "喫茶店でコーヒーを飲みます。": { id: "Saya minum kopi di kedai kopi.", kana: "きっさてんでコーヒーをのみます。" },
  "切手を買います。": { id: "Saya membeli prangko.", kana: "きってをかいます。" },
  "切符を買いました。": { id: "Saya sudah membeli tiket.", kana: "きっぷをかいました。" },
  "昨日は休みでした。": { id: "Kemarin adalah hari libur.", kana: "きのうはやすみでした。" },
  "九時です。": { id: "Sekarang jam sembilan.", kana: "くじです。" },
  "牛肉を食べます。": { id: "Saya makan daging sapi.", kana: "ぎゅうにくをたべます。" },
  "牛乳を飲みます。": { id: "Saya minum susu sapi.", kana: "ぎゅうにゅうをのみます。" },
  "今日はいい天気です。": { id: "Hari ini cuacanya bagus.", kana: "きょうはいいてんきです。" },
  "教室で勉強します。": { id: "Saya belajar di kelas.", kana: "きょうしつでべんきょうします。" },
  "兄弟はいますか。": { id: "Apakah kamu punya saudara?", kana: "きょうだいはいますか。" },
  "去年日本へ来ました。": { id: "Tahun lalu saya datang ke Jepang.", kana: "きょねんにほんへきました。" },
  "納豆が嫌いです。": { id: "Saya benci natto.", kana: "なっとうがきらいです。" },
  "紙を切ります。": { id: "Saya memotong kertas.", kana: "かみをきります。" },
  "シャツを着ます。": { id: "Saya memakai kemeja.", kana: "シャツをきます。" },
  "一キロ買います。": { id: "Saya membeli satu kilo.", kana: "いちキロかいます。" },
  "銀行へ行きます。": { id: "Saya pergi ke bank.", kana: "ぎんこうへいきます。" },
  "金曜日にパーティーをします。": { id: "Saya mengadakan pesta di hari Jumat.", kana: "きんようびにパーティーをします。" },
  "薬を飲みます。": { id: "Saya meminum obat.", kana: "くすりをのみます。" },
  "水をください。": { id: "Tolong beri saya air.", kana: "みずをください。" },
  "果物を食べます。": { id: "Saya memakan buah-buahan.", kana: "くだものをたべます。" },
  "口を開けます。": { id: "Saya membuka mulut.", kana: "くちをあけます。" },
  "靴を脱ぎます。": { id: "Saya melepas sepatu.", kana: "くつをぬぎます。" },
  "靴下を履きます。": { id: "Saya memakai kaus kaki.", kana: "くつしたをはきます。" },
  "お国はどちらですか。": { id: "Negaramu di mana?", kana: "おくにはどちらですか。" },
  "空が曇っています。": { id: "Langit sedang mendung.", kana: "そらがくもっています。" },
  "部屋が暗いです。": { id: "Kamarnya gelap.", kana: "へやがくらいです。" },
  "クラスで一番背が高いです。": { id: "Saya paling tinggi di kelas.", kana: "クラスでいちばんせがたかいです。" },
  "百グラムください。": { id: "Tolong beri saya seratus gram.", kana: "ひゃくグラムください。" },
  "友達が来ます。": { id: "Teman saya datang.", kana: "ともだちがきます。" },
  "車に乗ります。": { id: "Saya naik mobil.", kana: "くるまにのります。" },
  "黒い猫です。": { id: "Itu adalah kucing hitam.", kana: "くろいねこです。" },
  "警官に道を聞きます。": { id: "Saya bertanya jalan ke polisi.", kana: "けいかんにみちをききます。" },
  "今朝は早く起きました。": { id: "Pagi ini saya bangun awal.", kana: "けさははやくおきました。" },
  "テレビを消します。": { id: "Saya mematikan TV.", kana: "テレビをけします。" },
  "もう結構です。": { id: "Sudah cukup, terima kasih.", kana: "もうけっこうです。" },
  "来年結婚します。": { id: "Tahun depan saya akan menikah.", kana: "らいねんけっこんします。" },
  "月曜日は忙しいです。": { id: "Hari Senin saya sibuk.", kana: "げつようびはいそがしいです。" },
  "玄関で靴を脱ぎます。": { id: "Saya melepas sepatu di pintu masuk (genkan).", kana: "げんかんでくつをぬぎます。" },
  "お元気ですか。": { id: "Apa kabar?", kana: "おげんきですか。" },
  "五人います。": { id: "Ada lima orang.", kana: "ごにんいます。" },
  "交差点を右に曲がります。": { id: "Belok kanan di perempatan.", kana: "こうさてんをみぎにまがります。" },
  "紅茶を飲みます。": { id: "Saya meminum teh hitam.", kana: "こうちゃをのみます。" },
  "交番で道を聞きます。": { id: "Saya bertanya jalan di pos polisi.", kana: "こうばんでみちをききます。" },
  "コートを着ます。": { id: "Saya mengenakan mantel.", kana: "コートをきます。" },
  "コーヒーが好きです。": { id: "Saya suka kopi.", kana: "コーヒーがすきです。" },
  "ここは東京です。": { id: "Di sini adalah Tokyo.", kana: "ここはとうきょうです。" },
  "午後から雨が降ります。": { id: "Mulai siang/sore akan turun hujan.", kana: "ごごからあめがふります。" },
  "今日は九日です。": { id: "Hari ini adalah tanggal sembilan.", kana: "きょうはここのかです。" },
  "りんごが九つあります。": { id: "Ada sembilan buah apel.", kana: "りんごがここのつあります。" },
  "午前中に掃除します。": { id: "Saya bersih-bersih pada waktu pagi.", kana: "ごぜんちゅうにそうじします。" },
  "質問に答えます。": { id: "Saya menjawab pertanyaan.", kana: "しつもんにこたえます。" },
  "コップで水を飲みます。": { id: "Saya minum air menggunakan gelas.", kana: "コップでみずをのみます。" },
  "今年は暑いです。": { id: "Tahun ini terasa panas.", kana: "ことしはあついです。" },
  "新しい言葉を覚えます。": { id: "Saya menghafalkan kata baru.", kana: "あたらしいことばをおぼえます。" },
  "子供が遊んでいます。": { id: "Anak-anak sedang bermain.", kana: "こどもがあそんでいます。" },
  "この本は面白いです。": { id: "Buku ini menarik.", kana: "このほんはおもしろいです。" },
  "ご飯を食べます。": { id: "Saya makan nasi.", kana: "ごはんをたべます。" },
  "お金がなくて困ります。": { id: "Saya kesulitan karena tidak ada uang.", kana: "おかねがなくてこまります。" },
  "これは何ですか。": { id: "Ini apa?", kana: "これはなんですか。" },
  "今月は忙しいです。": { id: "Bulan ini sibuk.", kana: "こんげつはいそがしいです。" },
  "今週は暇です。": { id: "Minggu ini luang.", kana: "こんしゅうはひまです。" },
  "こんな問題は簡単です。": { id: "Masalah seperti ini itu mudah.", kana: "こんなもんだいはかんたんです。" },
  "今晩出かけます。": { id: "Malam ini saya pergi.", kana: "こんばんでかけます。" },
  "さあ、行きましょう。": { id: "Mari, ayo kita pergi.", kana: "さあ、いきましょう。" },
  "財布を忘れました。": { id: "Saya lupa dompet saya.", kana: "さいふをわすれました。" },
  "魚を食べます。": { id: "Saya makan ikan.", kana: "さかなをたべます。" },
  "お先に失礼します。": { id: "Saya permisi duluan.", kana: "おさきにしつれいします。" },
  "桜が咲いています。": { id: "Bunga sakura sedang mekar.", kana: "さくらがさいています。" },
  "作文を書きます。": { id: "Saya menulis karangan.", kana: "さくぶんをかきます。" },
  "傘を差します。": { id: "Saya menggunakan/membuka payung.", kana: "かさをさします。" },
  "雑誌を読みます。": { id: "Saya membaca majalah.", kana: "ざっしをよみます。" },
  "砂糖を入れます。": { id: "Saya memasukkan gula.", kana: "さとうをいれます。" },
  "今日は寒いです。": { id: "Hari ini dingin.", kana: "きょうはさむいです。" },
  
  // Batch 2 examples
  "ここは静かです。": { id: "Di sini sepi.", kana: "ここはしずかです。" },
  "机の下に猫がいます。": { id: "Ada kucing di bawah meja.", kana: "つくえのしたにねこがいます。" },
  "七時に起きます。": { id: "Saya bangun jam 7.", kana: "しちじにおきます。" },
  "質問があります。": { id: "Saya punya pertanyaan.", kana: "しつもんがあります。" },
  "自転車で学校に行きます。": { id: "Saya pergi ke sekolah naik sepeda.", kana: "じてんしゃでがっこうにいきます。" },
  "自動車を買います。": { id: "Saya membeli mobil.", kana: "じどうしゃをかいます。" },
  "病気で死にました。": { id: "Dia mati karena penyakit.", kana: "びょうきでしにました。" },
  "字引で調べます。": { id: "Mencarinya di kamus.", kana: "じびきでしらべます。" },
  "自分でします。": { id: "Saya melakukannya sendiri.", kana: "じぶんでします。" },
  "ドアが閉まります。": { id: "Pintu tertutup.", kana: "ドアがしまります。" },
  "窓を閉めます。": { id: "Saya menutup jendela.", kana: "まどをしめます。" },
  "ネクタイを締めます。": { id: "Saya memakai dasi.", kana: "ネクタイをしめます。" },
  "じゃあ、また明日。": { id: "Kalau begitu, sampai besok.", kana: "じゃあ、またあした。" },
  "写真を撮ります。": { id: "Saya mengambil foto.", kana: "しゃしんをとります。" },
  "白いシャツを着ます。": { id: "Saya memakai kemeja putih.", kana: "しろいシャツをきます。" },
  "十人います。": { id: "Ada sepuluh orang.", kana: "じゅうにんいます。" },
  "授業が始まります。": { id: "Pelajaran dimulai.", kana: "じゅぎょうがはじまります。" },
  "宿題をします。": { id: "Saya mengerjakan PR.", kana: "しゅくだいをします。" },
  "日本語が上手ですね。": { id: "Bahasa Jepangnya pintar ya.", kana: "にほんごがじょうずですね。" },
  "この鞄は丈夫です。": { id: "Tas ini kuat/awet.", kana: "このかばんはじょうぶです。" },
  "食堂でご飯を食べます。": { id: "Saya makan di kantin.", kana: "しょくどうでごはんをたべます。" },
  "彼の名前を知っていますか。": { id: "Apakah kamu tahu namanya?", kana: "かれのなまえをしっていますか。" },
  "毎朝新聞を読みます。": { id: "Saya membaca koran setiap pagi.", kana: "まいあさしんぶんをよみます。" },
  "水曜日にテストがあります。": { id: "Ada ujian pada hari Rabu.", kana: "すいようびにテストがあります。" },
  "タバコを吸いますか。": { id: "Apakah kamu menghisap rokok?", kana: "タバコをすいますか。" },
  "スカートを履きます。": { id: "Saya memakai rok.", kana: "スカートをはきます。" },
  "りんごが好きです。": { id: "Saya suka apel.", kana: "りんごがすきです。" },
  "人が少ないです。": { id: "Orangnya sedikit.", kana: "ひとがすくないです。" },
  "すぐ行きます。": { id: "Saya akan segera pergi.", kana: "すぐいきます。" },
  "少し疲れました。": { id: "Saya sedikit lelah.", kana: "すこしつかれました。" },
  "ストーブをつけます。": { id: "Saya menyalakan pemanas.", kana: "ストーブをつけます。" },
  "スプーンで食べます。": { id: "Saya makan dengan sendok.", kana: "スプーンでたべます。" },
  "スポーツが好きです。": { id: "Saya suka olahraga.", kana: "スポーツがすきです。" },
  "ズボンを履きます。": { id: "Saya memakai celana panjang.", kana: "ズボンをはきます。" },
  "東京に住んでいます。": { id: "Saya tinggal di Tokyo.", kana: "とうきょうにすんでいます。" },
  "スリッパを履きます。": { id: "Saya memakai sandal dalam rumah.", kana: "スリッパをはきます。" },
  "テニスをします。": { id: "Saya bermain tenis.", kana: "テニスをします。" },
  "椅子に座ります。": { id: "Saya duduk di kursi.", kana: "いすにすわります。" },
  "背が高いです。": { id: "Dia tinggi badannya.", kana: "せがたかいです。" },
  "生徒がたくさんいます。": { id: "Ada banyak murid.", kana: "せいとがたくさんいます。" },
  "セーターを着ます。": { id: "Saya memakai sweter.", kana: "セーターをきます。" },
  "石鹸で手を洗います。": { id: "Saya mencuci tangan dengan sabun.", kana: "せっけんでてをあらいます。" },
  "背広を着ます。": { id: "Saya memakai jas/setelan.", kana: "せびろをきます。" },
  "ゼロから始めます。": { id: "Saya memulainya dari nol.", kana: "ゼロからはじめます。" },
  "千円です。": { id: "Seribu yen.", kana: "せんえんです。" },
  "先月日本に来ました。": { id: "Bulan lalu saya datang ke Jepang.", kana: "せんげつにほんへきました。" },
  "先週は忙しかったです。": { id: "Minggu lalu saya sibuk.", kana: "せんしゅうはいそがしかったです。" },
  "先生に聞きます。": { id: "Saya bertanya kepada guru.", kana: "せんせいにききます。" },
  "洗濯をします。": { id: "Saya mencuci pakaian.", kana: "せんたくをします。" },
  "全部でいくらですか。": { id: "Totalnya berapa harganya?", kana: "ぜんぶでいくらですか。" },
  "部屋の掃除をします。": { id: "Saya membersihkan kamar.", kana: "へやのそうじをします。" },
  "そこに座ってください。": { id: "Silakan duduk di situ.", kana: "そこにすわってください。" },
  "そちらへ行きます。": { id: "Saya pergi ke sebelah situ.", kana: "そちらへいきます。" },
  "その本をください。": { id: "Tolong berikan buku itu.", kana: "そのほんをください。" },
  "駅のそばにあります。": { id: "Itu ada di samping/dekat stasiun.", kana: "えきのそばにあります。" },
  "空が青いです。": { id: "Langitnya berwarna biru.", kana: "そらがあおいです。" },
  "それは私の辞書です。": { id: "Itu adalah kamus saya.", kana: "それはわたしのじしょです。" },
  "それでは、また。": { id: "Kalau begitu, sampai jumpa lagi.", kana: "それでは、また。" }
};

let fixCount = 0;
data.vocabulary_n5.forEach(vocab => {
  if (vocab.examples && vocab.examples.length > 0) {
    const ex = vocab.examples[0];
    if (ex.id && ex.id.includes('(contoh)')) {
      const match = translations[ex.jp];
      if (match) {
        ex.id = match.id;
        ex.kana = match.kana;
        fixCount++;
      }
    }
  }
});

fs.writeFileSync(dataPath, JSON.stringify(data, null, 2), 'utf8');
console.log('Berhasil memperbaiki', fixCount, 'contoh kalimat!');
