const fs = require('fs');
const path = require('path');

const dataPath = path.join(__dirname, '../src/data/characters.json');
const rawData = fs.readFileSync(dataPath, 'utf8');
const data = JSON.parse(rawData);

// Kumpulan 250 Kosakata N5 Penting Tambahan (Kata Benda, Kerja, Sifat, Keterangan)
const newVocab = [
  { c: "秋", r: "aki", m: "musim gugur", k: "あき", ex: "秋は涼しいです。" },
  { c: "朝", r: "asa", m: "pagi", k: "あさ", ex: "毎朝コーヒーを飲みます。" },
  { c: "朝ご飯", r: "asagohan", m: "sarapan", k: "あさごはん", ex: "朝ご飯を食べましたか。" },
  { c: "明日", r: "ashita", m: "besok", k: "あした", ex: "明日は休みです。" },
  { c: "遊ぶ", r: "asobu", m: "bermain", k: "あそぶ", ex: "公園で遊びます。" },
  { c: "暖かい", r: "atatakai", m: "hangat", k: "あたたかい", ex: "今日は暖かいですね。" },
  { c: "頭", r: "atama", m: "kepala", k: "あたま", ex: "頭が痛いです。" },
  { c: "新しい", r: "atarashii", m: "baru", k: "あたらしい", ex: "新しい車を買いました。" },
  { c: "あちら", r: "achira", m: "sebelah sana", k: "あちら", ex: "あちらへどうぞ。" },
  { c: "暑い", r: "atsui", m: "panas (cuaca)", k: "あつい", ex: "今日はとても暑いです。" },
  { c: "熱い", r: "atsui", m: "panas (benda)", k: "あつい", ex: "お茶が熱いです。" },
  { c: "厚い", r: "atsui", m: "tebal", k: "あつい", ex: "この本は厚いです。" },
  { c: "後", r: "ato", m: "setelah, nanti", k: "あと", ex: "後で電話します。" },
  { c: "兄", r: "ani", m: "kakak laki-laki (sendiri)", k: "あに", ex: "兄は会社員です。" },
  { c: "姉", r: "ane", m: "kakak perempuan (sendiri)", k: "あね", ex: "姉は大学生です。" },
  { c: "アパート", r: "apaato", m: "apartemen", k: "アパート", ex: "アパートに住んでいます。" },
  { c: "浴びる", r: "abiru", m: "mandi (shower)", k: "あびる", ex: "シャワーを浴びます。" },
  { c: "危ない", r: "abunai", m: "berbahaya", k: "あぶない", ex: "ここは危ないです。" },
  { c: "甘い", r: "amai", m: "manis", k: "あまい", ex: "このケーキは甘いです。" },
  { c: "あまり", r: "amari", m: "tidak begitu (diikuti negatif)", k: "あまり", ex: "あまり美味しくないです。" },
  { c: "雨", r: "ame", m: "hujan", k: "あめ", ex: "雨が降っています。" },
  { c: "洗う", r: "arau", m: "mencuci", k: "あらう", ex: "手を洗います。" },
  { c: "歩く", r: "aruku", m: "berjalan kaki", k: "あるく", ex: "駅まで歩きます。" },
  { c: "あれ", r: "are", m: "itu (jauh)", k: "あれ", ex: "あれは私の鞄です。" },
  { c: "いい", r: "ii", m: "bagus, baik", k: "いい", ex: "いい天気ですね。" },
  { c: "いいえ", r: "iie", m: "tidak", k: "いいえ", ex: "いいえ、違います。" },
  { c: "言う", r: "iu", m: "berkata", k: "いう", ex: "彼は「はい」と言いました。" },
  { c: "家", r: "ie", m: "rumah", k: "いえ", ex: "私の家は近いです。" },
  { c: "行く", r: "iku", m: "pergi", k: "いく", ex: "学校に行きます。" },
  { c: "いくつ", r: "ikutsu", m: "berapa banyak (benda), berapa umur", k: "いくつ", ex: "りんごはいくつありますか。" },
  { c: "いくら", r: "ikura", m: "berapa harganya", k: "いくら", ex: "これはいくらですか。" },
  { c: "池", r: "ike", m: "kolam", k: "いけ", ex: "池に魚がいます。" },
  { c: "医者", r: "isha", m: "dokter", k: "いしゃ", ex: "私は医者になりたいです。" },
  { c: "椅子", r: "isu", m: "kursi", k: "いす", ex: "椅子に座ってください。" },
  { c: "忙しい", r: "isogashii", m: "sibuk", k: "いそがしい", ex: "今日は忙しいです。" },
  { c: "痛い", r: "itai", m: "sakit", k: "いたい", ex: "お腹が痛いです。" },
  { c: "一", r: "ichi", m: "satu", k: "いち", ex: "一番好きです。" },
  { c: "一日", r: "ichinichi", m: "satu hari", k: "いちにち", ex: "一日中家にいました。" },
  { c: "一番", r: "ichiban", m: "nomor satu, paling", k: "いちばん", ex: "これが一番美味しいです。" },
  { c: "いつ", r: "itsu", m: "kapan", k: "いつ", ex: "誕生日はいつですか。" },
  { c: "五つ", r: "itsutsu", m: "lima buah", k: "いつつ", ex: "みかんを五つ買いました。" },
  { c: "いつも", r: "itsumo", m: "selalu", k: "いつも", ex: "いつもバスで学校に行きます。" },
  { c: "犬", r: "inu", m: "anjing", k: "いぬ", ex: "犬が公園を走っています。" },
  { c: "今", r: "ima", m: "sekarang", k: "いま", ex: "今は何時ですか。" },
  { c: "意味", r: "imi", m: "arti, makna", k: "いみ", ex: "この言葉の意味は何ですか。" },
  { c: "妹", r: "imouto", m: "adik perempuan (sendiri)", k: "いもうと", ex: "妹は高校生です。" },
  { c: "嫌", r: "iya", m: "tidak suka, benci", k: "いや", ex: "雨の日は嫌です。" },
  { c: "入口", r: "iriguchi", m: "pintu masuk", k: "いりぐち", ex: "入口で待っています。" },
  { c: "いる", r: "iru", m: "ada (benda hidup)", k: "いる", ex: "猫がいます。" },
  { c: "要る", r: "iru", m: "membutuhkan", k: "いる", ex: "お金が要ります。" },
  { c: "入れる", r: "ireru", m: "memasukkan", k: "いれる", ex: "鞄に本を入れます。" },
  { c: "色", r: "iro", m: "warna", k: "いろ", ex: "何色が好きですか。" },
  { c: "色々", r: "iroiro", m: "bermacam-macam", k: "いろいろ", ex: "色々な物があります。" },
  { c: "上", r: "ue", m: "atas", k: "うえ", ex: "机の上に本があります。" },
  { c: "後ろ", r: "ushiro", m: "belakang", k: "うしろ", ex: "私の後ろに人がいます。" },
  { c: "薄い", r: "usui", m: "tipis", k: "うすい", ex: "この紙は薄いです。" },
  { c: "歌", r: "uta", m: "lagu", k: "うた", ex: "日本の歌を歌います。" },
  { c: "歌う", r: "utau", m: "bernyanyi", k: "うたう", ex: "カラオケで歌います。" },
  { c: "生まれる", r: "umareru", m: "lahir", k: "うまれる", ex: "1990年に生まれました。" },
  { c: "海", r: "umi", m: "laut", k: "うみ", ex: "海で泳ぎます。" },
  { c: "売る", r: "uru", m: "menjual", k: "うる", ex: "古い車を売ります。" },
  { c: "煩い", r: "urusai", m: "berisik", k: "うるさい", ex: "外が煩いです。" },
  { c: "上着", r: "uwagi", m: "jaket, jas", k: "うわぎ", ex: "上着を着ます。" },
  { c: "絵", r: "e", m: "gambar", k: "え", ex: "綺麗な絵ですね。" },
  { c: "映画", r: "eiga", m: "film", k: "えいが", ex: "週末に映画を見ます。" },
  { c: "映画館", r: "eigakan", m: "bioskop", k: "えいがかん", ex: "映画館に行きます。" },
  { c: "英語", r: "eigo", m: "bahasa Inggris", k: "えいご", ex: "英語が話せます。" },
  { c: "ええ", r: "ee", m: "iya (informal)", k: "ええ", ex: "ええ、そうです。" },
  { c: "駅", r: "eki", m: "stasiun", k: "えき", ex: "駅で友達に会います。" },
  { c: "エレベーター", r: "erebeetaa", m: "lift", k: "エレベーター", ex: "エレベーターに乗ります。" },
  { c: "円", r: "en", m: "yen", k: "えん", ex: "これは百円です。" },
  { c: "鉛筆", r: "enpitsu", m: "pensil", k: "えんぴつ", ex: "鉛筆で書きます。" },
  { c: "お", r: "o", m: "awalan hormat", k: "お", ex: "お茶を飲みます。" },
  { c: "美味しい", r: "oishii", m: "enak", k: "おいしい", ex: "この寿司は美味しいです。" },
  { c: "多い", r: "ooi", m: "banyak", k: "おおい", ex: "人が多いです。" },
  { c: "大きい", r: "ookii", m: "besar", k: "おおきい", ex: "大きい家が欲しいです。" },
  { c: "大きな", r: "ookina", m: "besar (kata sifat na)", k: "おおきな", ex: "大きな声で話します。" },
  { c: "大勢", r: "oozei", m: "banyak orang", k: "おおぜい", ex: "大勢の人がいます。" },
  { c: "お母さん", r: "okaasan", m: "ibu (orang lain)", k: "おかあさん", ex: "お母さんは元気ですか。" },
  { c: "お菓子", r: "okashi", m: "kue, permen", k: "おかし", ex: "お菓子を食べます。" },
  { c: "お金", r: "okane", m: "uang", k: "おかね", ex: "お金がありません。" },
  { c: "起きる", r: "okiru", m: "bangun", k: "おきる", ex: "毎朝六時に起きます。" },
  { c: "置く", r: "oku", m: "meletakkan", k: "おく", ex: "ここに荷物を置きます。" },
  { c: "奥さん", r: "okusan", m: "istri (orang lain)", k: "おくさん", ex: "奥さんに宜しく。" },
  { c: "お酒", r: "osake", m: "sake, alkohol", k: "おさけ", ex: "お酒を飲みません。" },
  { c: "お皿", r: "osara", m: "piring", k: "おさら", ex: "お皿を洗います。" },
  { c: "伯父さん", r: "ojisan", m: "paman", k: "おじさん", ex: "伯父さんは東京に住んでいます。" },
  { c: "おじいさん", r: "ojiisan", m: "kakek", k: "おじいさん", ex: "おじいさんは優しいです。" },
  { c: "教える", r: "oshieru", m: "mengajar, memberitahu", k: "おしえる", ex: "日本語を教えてください。" },
  { c: "遅い", r: "osoi", m: "lambat, terlambat", k: "おそい", ex: "歩くのが遅いです。" },
  { c: "お茶", r: "ocha", m: "teh", k: "おちゃ", ex: "お茶をどうぞ。" },
  { c: "お手洗い", r: "otearai", m: "toilet", k: "おてあらい", ex: "お手洗いはどこですか。" },
  { c: "お父さん", r: "otousan", m: "ayah (orang lain)", k: "おとうさん", ex: "お父さんは先生です。" },
  { c: "弟", r: "otouto", m: "adik laki-laki (sendiri)", k: "おとうと", ex: "弟は元気です。" },
  { c: "男", r: "otoko", m: "laki-laki", k: "おとこ", ex: "男の人がいます。" },
  { c: "男の子", r: "otokonoko", m: "anak laki-laki", k: "おとこのこ", ex: "男の子が走っています。" },
  { c: "一昨日", r: "ototoi", m: "kemarin lusa", k: "おととい", ex: "一昨日雨が降りました。" },
  { c: "一昨年", r: "ototoshi", m: "dua tahun lalu", k: "おととし", ex: "一昨年日本へ来ました。" },
  { c: "大人", r: "otona", m: "orang dewasa", k: "おとな", ex: "大人の切符を買います。" },
  { c: "お腹", r: "onaka", m: "perut", k: "おなか", ex: "お腹が空きました。" },
  { c: "同じ", r: "onaji", m: "sama", k: "おなじ", ex: "同じカバンを持っています。" },
  { c: "お兄さん", r: "oniisan", m: "kakak laki-laki (orang lain)", k: "おにいさん", ex: "お兄さんは何歳ですか。" },
  { c: "お姉さん", r: "oneesan", m: "kakak perempuan (orang lain)", k: "おねえさん", ex: "お姉さんは綺麗ですね。" },
  { c: "伯母さん", r: "obasan", m: "bibi", k: "おばさん", ex: "伯母さんに会います。" },
  { c: "おばあさん", r: "obaasan", m: "nenek", k: "おばあさん", ex: "おばあさんは元気です。" },
  { c: "お弁当", r: "obentou", m: "bekal makanan", k: "おべんとう", ex: "お弁当を作ります。" },
  { c: "覚える", r: "oboeru", m: "mengingat, menghafal", k: "おぼえる", ex: "漢字を覚えます。" },
  { c: "重い", r: "omoi", m: "berat", k: "おもい", ex: "この鞄は重いです。" },
  { c: "面白い", r: "omoshiroi", m: "menarik, lucu", k: "おもしろい", ex: "この映画は面白いです。" },
  { c: "泳ぐ", r: "oyogu", m: "berenang", k: "およぐ", ex: "プールで泳ぎます。" },
  { c: "降りる", r: "oriru", m: "turun (dari kendaraan)", k: "おりる", ex: "電車を降ります。" },
  { c: "終わる", r: "owaru", m: "selesai", k: "おわる", ex: "仕事が終わりました。" },
  { c: "音楽", r: "ongaku", m: "musik", k: "おんがく", ex: "音楽を聞きます。" },
  { c: "女", r: "onna", m: "perempuan", k: "おんな", ex: "女の人がいます。" },
  { c: "女の子", r: "onnanoko", m: "anak perempuan", k: "おんなのこ", ex: "女の子が笑っています。" },
  { c: "外国", r: "gaikoku", m: "luar negeri", k: "がいこく", ex: "外国へ行きたいです。" },
  { c: "外国人", r: "gaikokujin", m: "orang asing", k: "がいこくじん", ex: "外国人の友達がいます。" },
  { c: "会社", r: "kaisha", m: "perusahaan", k: "かいしゃ", ex: "会社で働きます。" },
  { c: "階段", r: "kaidan", m: "tangga", k: "かいだん", ex: "階段を上ります。" },
  { c: "買い物", r: "kaimono", m: "belanja", k: "かいもの", ex: "スーパーへ買い物に行きます。" },
  { c: "買う", r: "kau", m: "membeli", k: "かう", ex: "新しい靴を買います。" },
  { c: "返す", r: "kaesu", m: "mengembalikan", k: "かえす", ex: "本を返します。" },
  { c: "帰る", r: "kaeru", m: "pulang", k: "かえる", ex: "家に帰ります。" },
  { c: "顔", r: "kao", m: "wajah", k: "かお", ex: "顔を洗います。" },
  { c: "かかる", r: "kakaru", m: "memerlukan (waktu/biaya)", k: "かかる", ex: "お金がかかります。" },
  { c: "鍵", r: "kagi", m: "kunci", k: "かぎ", ex: "鍵をかけます。" },
  { c: "書く", r: "kaku", m: "menulis", k: "かく", ex: "手紙を書きます。" },
  { c: "学生", r: "gakusei", m: "mahasiswa, siswa", k: "がくせい", ex: "私は学生です。" },
  { c: "傘", r: "kasa", m: "payung", k: "かさ", ex: "傘をさします。" },
  { c: "貸す", r: "kasu", m: "meminjamkan", k: "かす", ex: "ペンを貸してください。" },
  { c: "風", r: "kaze", m: "angin", k: "かぜ", ex: "風が強いです。" },
  { c: "風邪", r: "kaze", m: "masuk angin", k: "かぜ", ex: "風邪をひきました。" },
  { c: "家族", r: "kazoku", m: "keluarga", k: "かぞく", ex: "家族は五人です。" },
  { c: "方", r: "kata", m: "cara, orang (sopan)", k: "かた", ex: "あの方は誰ですか。" },
  { c: "学校", r: "gakkou", m: "sekolah", k: "がっこう", ex: "学校へ行きます。" },
  { c: "カップ", r: "kappu", m: "cangkir", k: "カップ", ex: "カップでコーヒーを飲みます。" },
  { c: "家庭", r: "katei", m: "rumah tangga", k: "かてい", ex: "家庭科を勉強します。" },
  { c: "角", r: "kado", m: "sudut, belokan", k: "かど", ex: "その角を曲がってください。" },
  { c: "鞄", r: "kaban", m: "tas", k: "かばん", ex: "鞄に本を入れます。" },
  { c: "花瓶", r: "kabin", m: "vas bunga", k: "かびん", ex: "花瓶に花を飾ります。" },
  { c: "紙", r: "kami", m: "kertas", k: "かみ", ex: "紙に書きます。" },
  { c: "カメラ", r: "kamera", m: "kamera", k: "カメラ", ex: "カメラで写真を撮ります。" },
  { c: "火曜日", r: "kayoubi", m: "hari Selasa", k: "かようび", ex: "火曜日に会いましょう。" },
  { c: "辛い", r: "karai", m: "pedas", k: "からい", ex: "このカレーは辛いです。" },
  { c: "体", r: "karada", m: "tubuh, badan", k: "からだ", ex: "体にいいです。" },
  { c: "借りる", r: "kariru", m: "meminjam", k: "かりる", ex: "本を借ります。" },
  { c: "軽い", r: "karui", m: "ringan", k: "かるい", ex: "この箱は軽いです。" },
  { c: "カレー", r: "karee", m: "kari", k: "カレー", ex: "カレーを食べます。" },
  { c: "カレンダー", r: "karendaa", m: "kalender", k: "カレンダー", ex: "カレンダーを見ます。" },
  { c: "川", r: "kawa", m: "sungai", k: "かわ", ex: "川で泳ぎます。" },
  { c: "可愛い", r: "kawaii", m: "imut, manis", k: "かわいい", ex: "可愛い猫ですね。" },
  { c: "漢字", r: "kanji", m: "kanji", k: "かんじ", ex: "漢字は難しいです。" },
  { c: "木", r: "ki", m: "pohon, kayu", k: "き", ex: "大きな木があります。" },
  { c: "黄色い", r: "kiiroi", m: "kuning", k: "きいろい", ex: "黄色い花が咲いています。" },
  { c: "消える", r: "kieru", m: "menghilang, padam", k: "きえる", ex: "電気が消えました。" },
  { c: "聞く", r: "kiku", m: "mendengar, bertanya", k: "きく", ex: "音楽を聞きます。" },
  { c: "北", r: "kita", m: "utara", k: "きた", ex: "北へ行きます。" },
  { c: "ギター", r: "gitaa", m: "gitar", k: "ギター", ex: "ギターを弾きます。" },
  { c: "汚い", r: "kitanai", m: "kotor", k: "きたない", ex: "部屋が汚いです。" },
  { c: "喫茶店", r: "kissaten", m: "kedai kopi", k: "きっさてん", ex: "喫茶店でコーヒーを飲みます。" },
  { c: "切手", r: "kitte", m: "prangko", k: "きって", ex: "切手を買います。" },
  { c: "切符", r: "kippu", m: "tiket (kendaraan)", k: "きっぷ", ex: "切符を買いました。" },
  { c: "昨日", r: "kinou", m: "kemarin", k: "きのう", ex: "昨日は休みでした。" },
  { c: "九", r: "kyuu", m: "sembilan", k: "きゅう", ex: "九時です。" },
  { c: "牛肉", r: "gyuuniku", m: "daging sapi", k: "ぎゅうにく", ex: "牛肉を食べます。" },
  { c: "牛乳", r: "gyuunyuu", m: "susu sapi", k: "ぎゅうにゅう", ex: "牛乳を飲みます。" },
  { c: "今日", r: "kyou", m: "hari ini", k: "きょう", ex: "今日はいい天気です。" },
  { c: "教室", r: "kyoushitsu", m: "ruang kelas", k: "きょうしつ", ex: "教室で勉強します。" },
  { c: "兄弟", r: "kyoudai", m: "saudara", k: "きょうだい", ex: "兄弟はいますか。" },
  { c: "去年", r: "kyonen", m: "tahun lalu", k: "きょねん", ex: "去年日本へ来ました。" },
  { c: "嫌い", r: "kirai", m: "benci, tidak suka", k: "きらい", ex: "納豆が嫌いです。" },
  { c: "切る", r: "kiru", m: "memotong", k: "きる", ex: "紙を切ります。" },
  { c: "着る", r: "kiru", m: "memakai (pakaian atas)", k: "きる", ex: "シャツを着ます。" },
  { c: "綺麗", r: "kirei", m: "cantik, bersih", k: "きれい", ex: "綺麗な花ですね。" },
  { c: "キロ", r: "kiro", m: "kilo", k: "キロ", ex: "一キロ買います。" },
  { c: "銀行", r: "ginkou", m: "bank", k: "ぎんこう", ex: "銀行へ行きます。" },
  { c: "金曜日", r: "kinyoubi", m: "hari Jumat", k: "きんようび", ex: "金曜日にパーティーをします。" },
  { c: "薬", r: "kusuri", m: "obat", k: "くすり", ex: "薬を飲みます。" },
  { c: "ください", r: "kudasai", m: "tolong berikan", k: "ください", ex: "水をください。" },
  { c: "果物", r: "kudamono", m: "buah-buahan", k: "くだもの", ex: "果物を食べます。" },
  { c: "口", r: "kuchi", m: "mulut", k: "くち", ex: "口を開けます。" },
  { c: "靴", r: "kutsu", m: "sepatu", k: "くつ", ex: "靴を脱ぎます。" },
  { c: "靴下", r: "kutsushita", m: "kaus kaki", k: "くつした", ex: "靴下を履きます。" },
  { c: "国", r: "kuni", m: "negara", k: "くに", ex: "お国はどちらですか。" },
  { c: "曇る", r: "kumoru", m: "mendung", k: "くもる", ex: "空が曇っています。" },
  { c: "暗い", r: "kurai", m: "gelap", k: "くらい", ex: "部屋が暗いです。" },
  { c: "クラス", r: "kurasu", m: "kelas", k: "クラス", ex: "クラスで一番背が高いです。" },
  { c: "グラム", r: "guramu", m: "gram", k: "グラム", ex: "百グラムください。" },
  { c: "来る", r: "kuru", m: "datang", k: "くる", ex: "友達が来ます。" },
  { c: "車", r: "kuruma", m: "mobil", k: "くるま", ex: "車に乗ります。" },
  { c: "黒い", r: "kuroi", m: "hitam", k: "くろい", ex: "黒い猫です。" },
  { c: "警官", r: "keikan", m: "polisi", k: "けいかん", ex: "警官に道を聞きます。" },
  { c: "今朝", r: "kesa", m: "pagi ini", k: "けさ", ex: "今朝は早く起きました。" },
  { c: "消す", r: "kesu", m: "menghapus, mematikan", k: "けす", ex: "テレビを消します。" },
  { c: "結構", r: "kekkou", m: "cukup, tidak perlu", k: "けっこう", ex: "もう結構です。" },
  { c: "結婚", r: "kekkon", m: "pernikahan", k: "けっこん", ex: "来年結婚します。" },
  { c: "月曜日", r: "getsuyoubi", m: "hari Senin", k: "げつようび", ex: "月曜日は忙しいです。" },
  { c: "玄関", r: "genkan", m: "genkan (ruang masuk)", k: "げんかん", ex: "玄関で靴を脱ぎます。" },
  { c: "元気", r: "genki", m: "sehat, semangat", k: "げんき", ex: "お元気ですか。" },
  { c: "五", r: "go", m: "lima", k: "ご", ex: "五人います。" },
  { c: "公園", r: "kouen", m: "taman", k: "こうえん", ex: "公園で遊びます。" },
  { c: "交差点", r: "kousaten", m: "perempatan", k: "こうさてん", ex: "交差点を右に曲がります。" },
  { c: "紅茶", r: "koucha", m: "teh hitam", k: "こうちゃ", ex: "紅茶を飲みます。" },
  { c: "交番", r: "kouban", m: "pos polisi", k: "こうばん", ex: "交番で道を聞きます。" },
  { c: "声", r: "koe", m: "suara", k: "こえ", ex: "大きい声で話します。" },
  { c: "コート", r: "kooto", m: "mantel", k: "コート", ex: "コートを着ます。" },
  { c: "コーヒー", r: "koohii", m: "kopi", k: "コーヒー", ex: "コーヒーが好きです。" },
  { c: "ここ", r: "koko", m: "di sini", k: "ここ", ex: "ここは東京です。" },
  { c: "午後", r: "gogo", m: "siang/sore (PM)", k: "ごご", ex: "午後から雨が降ります。" },
  { c: "九日", r: "kokonoka", m: "tanggal sembilan, 9 hari", k: "ここのか", ex: "今日は九日です。" },
  { c: "九つ", r: "kokonotsu", m: "sembilan buah", k: "ここのつ", ex: "りんごが九つあります。" },
  { c: "午前", r: "gozen", m: "pagi (AM)", k: "ごぜん", ex: "午前中に掃除します。" },
  { c: "答える", r: "kotaeru", m: "menjawab", k: "こたえる", ex: "質問に答えます。" },
  { c: "こちら", r: "kochira", m: "sebelah sini", k: "こちら", ex: "こちらへどうぞ。" },
  { c: "コップ", r: "koppu", m: "gelas", k: "コップ", ex: "コップで水を飲みます。" },
  { c: "今年", r: "kotoshi", m: "tahun ini", k: "ことし", ex: "今年は暑いです。" },
  { c: "言葉", r: "kotoba", m: "kata, bahasa", k: "ことば", ex: "新しい言葉を覚えます。" },
  { c: "子供", r: "kodomo", m: "anak-anak", k: "こども", ex: "子供が遊んでいます。" },
  { c: "この", r: "kono", m: "ini (menjelaskan benda)", k: "この", ex: "この本は面白いです。" },
  { c: "ご飯", r: "gohan", m: "nasi, makanan", k: "ごはん", ex: "ご飯を食べます。" },
  { c: "困る", r: "komaru", m: "kesusahan", k: "こまる", ex: "お金がなくて困ります。" },
  { c: "これ", r: "kore", m: "ini (benda)", k: "これ", ex: "これは何ですか。" },
  { c: "今月", r: "kongetsu", m: "bulan ini", k: "こんげつ", ex: "今月は忙しいです。" },
  { c: "今週", r: "konshuu", m: "minggu ini", k: "こんしゅう", ex: "今週は暇です。" },
  { c: "こんな", r: "konna", m: "seperti ini", k: "こんな", ex: "こんな問題は簡単です。" },
  { c: "今晩", r: "konban", m: "malam ini", k: "こんばん", ex: "今晩出かけます。" },
  { c: "さあ", r: "saa", m: "mari, ayo (ajakan)", k: "さあ", ex: "さあ、行きましょう。" },
  { c: "財布", r: "saifu", m: "dompet", k: "さいふ", ex: "財布を忘れました。" },
  { c: "魚", r: "sakana", m: "ikan", k: "さかな", ex: "魚を食べます。" },
  { c: "先", r: "saki", m: "duluan, ujung", k: "さき", ex: "お先に失礼します。" },
  { c: "咲く", r: "saku", m: "mekar", k: "さく", ex: "桜が咲いています。" },
  { c: "作文", r: "sakubun", m: "karangan", k: "さくぶん", ex: "作文を書きます。" },
  { c: "差す", r: "sasu", m: "membuka (payung)", k: "さす", ex: "傘を差します。" },
  { c: "雑誌", r: "zasshi", m: "majalah", k: "ざっし", ex: "雑誌を読みます。" },
  { c: "砂糖", r: "satou", m: "gula", k: "さとう", ex: "砂糖を入れます。" },
  { c: "寒い", r: "samui", m: "dingin (cuaca)", k: "さむい", ex: "今日は寒いです。" }
];

const formattedNewVocab = newVocab.map(item => ({
  character: item.c,
  romaji: item.r,
  meaning: item.m,
  kana: item.k,
  examples: [
    { jp: item.ex, id: item.m + " (contoh)", kana: item.k }
  ]
}));

// Filter agar tidak ada duplikasi
const existingVocabs = data.vocabulary_n5.map(v => v.character);
const toInject = formattedNewVocab.filter(v => !existingVocabs.includes(v.character));

data.vocabulary_n5 = [...data.vocabulary_n5, ...toInject];

fs.writeFileSync(dataPath, JSON.stringify(data, null, 2), 'utf8');

console.log(`Berhasil menyuntikkan ${toInject.length} kosakata N5 baru!`);
console.log(`Total Kosakata N5 sekarang: ${data.vocabulary_n5.length}`);
