const fs = require('fs');
const path = require('path');

const charactersFile = path.join(__dirname, '../src', 'data', 'characters.json');
const charactersData = JSON.parse(fs.readFileSync(charactersFile, 'utf8'));

// REAL JLPT N4 VOCABULARY (Authentic list, no duplicates)
const realN4Vocab = [
  { "character": "挨拶", "romaji": "aisatsu", "meaning": "salam" },
  { "character": "間", "romaji": "aida", "meaning": "di antara" },
  { "character": "合う", "romaji": "au", "meaning": "cocok, sesuai" },
  { "character": "あかちゃん", "romaji": "akachan", "meaning": "bayi" },
  { "character": "上る", "romaji": "agaru", "meaning": "naik" },
  { "character": "赤ん坊", "romaji": "akanbou", "meaning": "bayi" },
  { "character": "空く", "romaji": "aku", "meaning": "kosong, luang" },
  { "character": "浅い", "romaji": "asai", "meaning": "dangkal" },
  { "character": "味", "romaji": "aji", "meaning": "rasa" },
  { "character": "明日", "romaji": "asu", "meaning": "besok" },
  { "character": "遊び", "romaji": "asobi", "meaning": "permainan, bermain" },
  { "character": "集める", "romaji": "atsumeru", "meaning": "mengumpulkan" },
  { "character": "集まる", "romaji": "atsumaru", "meaning": "berkumpul" },
  { "character": "謝る", "romaji": "ayamaru", "meaning": "meminta maaf" },
  { "character": "安心", "romaji": "anshin", "meaning": "lega, tenang" },
  { "character": "安全", "romaji": "anzen", "meaning": "aman" },
  { "character": "あんな", "romaji": "anna", "meaning": "seperti itu (jauh)" },
  { "character": "以下", "romaji": "ika", "meaning": "di bawah, kurang dari" },
  { "character": "以外", "romaji": "igai", "meaning": "selain" },
  { "character": "医学", "romaji": "igaku", "meaning": "ilmu kedokteran" },
  { "character": "生きる", "romaji": "ikiru", "meaning": "hidup" },
  { "character": "意見", "romaji": "iken", "meaning": "pendapat" },
  { "character": "石", "romaji": "ishi", "meaning": "batu" },
  { "character": "いじめる", "romaji": "ijimeru", "meaning": "menindas, membully" },
  { "character": "以上", "romaji": "ijou", "meaning": "di atas, lebih dari" },
  { "character": "急ぐ", "romaji": "isogu", "meaning": "bergegas" },
  { "character": "致す", "romaji": "itasu", "meaning": "melakukan (merendahkan diri)" },
  { "character": "一度", "romaji": "ichido", "meaning": "sekali" },
  { "character": "一生懸命", "romaji": "isshoukenmei", "meaning": "sekuat tenaga" },
  { "character": "糸", "romaji": "ito", "meaning": "benang" },
  { "character": "以内", "romaji": "inai", "meaning": "di dalam (batas)" },
  { "character": "田舎", "romaji": "inaka", "meaning": "pedesaan, kampung halaman" },
  { "character": "祈る", "romaji": "inoru", "meaning": "berdoa" },
  { "character": "いらっしゃる", "romaji": "irassharu", "meaning": "datang, pergi, ada (hormat)" },
  { "character": "植える", "romaji": "ueru", "meaning": "menanam" },
  { "character": "伺う", "romaji": "ukagau", "meaning": "berkunjung, bertanya (merendahkan diri)" },
  { "character": "受付", "romaji": "uketsuke", "meaning": "resepsionis" },
  { "character": "受ける", "romaji": "ukeru", "meaning": "mengikuti (ujian), menerima" },
  { "character": "動く", "romaji": "ugoku", "meaning": "bergerak" },
  { "character": "うそ", "romaji": "uso", "meaning": "bohong" },
  { "character": "打つ", "romaji": "utsu", "meaning": "memukul" },
  { "character": "美しい", "romaji": "utsukushii", "meaning": "indah, cantik" },
  { "character": "写す", "romaji": "utsusu", "meaning": "menyalin, memotret" },
  { "character": "移る", "romaji": "utsuru", "meaning": "pindah" },
  { "character": "腕", "romaji": "ude", "meaning": "lengan" },
  { "character": "裏", "romaji": "ura", "meaning": "bagian belakang, kebalikan" },
  { "character": "売り場", "romaji": "uriba", "meaning": "tempat penjualan" },
  { "character": "運転手", "romaji": "untenshu", "meaning": "sopir" },
  { "character": "運動", "romaji": "undou", "meaning": "olahraga" },
  { "character": "エスカレーター", "romaji": "esukareetaa", "meaning": "eskalator" },
  { "character": "枝", "romaji": "eda", "meaning": "cabang, ranting" },
  { "character": "選ぶ", "romaji": "erabu", "meaning": "memilih" },
  { "character": "遠慮", "romaji": "enryo", "meaning": "sungkan, menahan diri" },
  { "character": "おいでになる", "romaji": "oide ni naru", "meaning": "datang, ada (hormat)" },
  { "character": "お祝い", "romaji": "oiwai", "meaning": "perayaan, hadiah" },
  { "character": "オートバイ", "romaji": "ootobai", "meaning": "sepeda motor" },
  { "character": "お嬢さん", "romaji": "ojousan", "meaning": "anak perempuan (orang lain)" },
  { "character": "お宅", "romaji": "otaku", "meaning": "rumah (orang lain)" },
  { "character": "落ちる", "romaji": "ochiru", "meaning": "jatuh" },
  { "character": "おっしゃる", "romaji": "ossharu", "meaning": "berkata (hormat)" },
  { "character": "夫", "romaji": "otto", "meaning": "suami (sendiri)" },
  { "character": "落とす", "romaji": "otosu", "meaning": "menjatuhkan" },
  { "character": "踊り", "romaji": "odori", "meaning": "tarian" },
  { "character": "踊る", "romaji": "odoru", "meaning": "menari" },
  { "character": "驚く", "romaji": "odoroku", "meaning": "terkejut" },
  { "character": "お祭り", "romaji": "omatsuri", "meaning": "festival" },
  { "character": "お見舞い", "romaji": "omimai", "meaning": "menjenguk orang sakit" },
  { "character": "お土産", "romaji": "omiyage", "meaning": "oleh-oleh" },
  { "character": "思い出す", "romaji": "omoidasu", "meaning": "teringat, mengenang" },
  { "character": "思う", "romaji": "omou", "meaning": "berpikir, merasa" },
  { "character": "おもちゃ", "romaji": "omocha", "meaning": "mainan" },
  { "character": "表", "romaji": "omote", "meaning": "permukaan, bagian depan" },
  { "character": "親", "romaji": "oya", "meaning": "orang tua" },
  { "character": "泳ぎ方", "romaji": "oyogikata", "meaning": "cara berenang" },
  { "character": "下りる", "romaji": "oriru", "meaning": "turun (dari tempat tinggi)" },
  { "character": "折る", "romaji": "oru", "meaning": "melipat, mematahkan" },
  { "character": "お礼", "romaji": "orei", "meaning": "terima kasih, balasan" },
  { "character": "終わる", "romaji": "owaru", "meaning": "selesai" },
  { "character": "海岸", "romaji": "kaigan", "meaning": "pantai" },
  { "character": "会議", "romaji": "kaigi", "meaning": "rapat" },
  { "character": "会議室", "romaji": "kaigishitsu", "meaning": "ruang rapat" },
  { "character": "会場", "romaji": "kaijou", "meaning": "tempat acara" },
  { "character": "会話", "romaji": "kaiwa", "meaning": "percakapan" },
  { "character": "帰り", "romaji": "kaeri", "meaning": "kepulangan" },
  { "character": "変える", "romaji": "kaeru", "meaning": "mengubah" },
  { "character": "科学", "romaji": "kagaku", "meaning": "sains, ilmu pengetahuan" },
  { "character": "鏡", "romaji": "kagami", "meaning": "cermin" },
  { "character": "掛ける", "romaji": "kakeru", "meaning": "menggantung, menelepon" },
  { "character": "飾る", "romaji": "kazaru", "meaning": "menghias" },
  { "character": "火事", "romaji": "kaji", "meaning": "kebakaran" },
  { "character": "ガス", "romaji": "gasu", "meaning": "gas" },
  { "character": "硬い", "romaji": "katai", "meaning": "keras" },
  { "character": "形", "romaji": "katachi", "meaning": "bentuk" },
  { "character": "片付ける", "romaji": "katadukeru", "meaning": "membereskan" },
  { "character": "課長", "romaji": "kachou", "meaning": "kepala bagian" },
  { "character": "勝つ", "romaji": "katsu", "meaning": "menang" },
  { "character": "家内", "romaji": "kanai", "meaning": "istri (sendiri)" },
  { "character": "悲しい", "romaji": "kanashii", "meaning": "sedih" },
  { "character": "必ず", "romaji": "kanarazu", "meaning": "pasti" },
  { "character": "お金持ち", "romaji": "okanemochi", "meaning": "orang kaya" },
  { "character": "彼女", "romaji": "kanojo", "meaning": "dia (perempuan), pacar" },
  { "character": "壁", "romaji": "kabe", "meaning": "dinding" },
  { "character": "髪", "romaji": "kami", "meaning": "rambut" },
  { "character": "かむ", "romaji": "kamu", "meaning": "menggigit, mengunyah" },
  { "character": "通う", "romaji": "kayou", "meaning": "pulang pergi (rutin)" },
  { "character": "彼", "romaji": "kare", "meaning": "dia (laki-laki), pacar" },
  { "character": "乾く", "romaji": "kawaku", "meaning": "mengering" },
  { "character": "代わり", "romaji": "kawari", "meaning": "pengganti" },
  { "character": "変わる", "romaji": "kawaru", "meaning": "berubah" },
  { "character": "考える", "romaji": "kangaeru", "meaning": "memikirkan" },
  { "character": "関係", "romaji": "kankei", "meaning": "hubungan" },
  { "character": "看護師", "romaji": "kangoshi", "meaning": "perawat" },
  { "character": "簡単", "romaji": "kantan", "meaning": "mudah, gampang" },
  { "character": "気", "romaji": "ki", "meaning": "perasaan, pikiran" },
  { "character": "機会", "romaji": "kikai", "meaning": "kesempatan" },
  { "character": "危険", "romaji": "kiken", "meaning": "bahaya" },
  { "character": "聞こえる", "romaji": "kikoeru", "meaning": "terdengar" },
  { "character": "汽車", "romaji": "kisha", "meaning": "kereta api uap" },
  { "character": "技術", "romaji": "gijutsu", "meaning": "teknologi, teknik" },
  { "character": "季節", "romaji": "kisetsu", "meaning": "musim" },
  { "character": "規則", "romaji": "kisoku", "meaning": "peraturan" },
  { "character": "絹", "romaji": "kinu", "meaning": "sutra" },
  { "character": "厳しい", "romaji": "kibishii", "meaning": "tegas, ketat" },
  { "character": "気分", "romaji": "kibun", "meaning": "perasaan, kondisi" },
  { "character": "決まる", "romaji": "kimaru", "meaning": "ditentukan" },
  { "character": "君", "romaji": "kimi", "meaning": "kamu (informal laki-laki)" },
  { "character": "決める", "romaji": "kimeru", "meaning": "memutuskan" },
  { "character": "気持ち", "romaji": "kimochi", "meaning": "perasaan" },
  { "character": "着物", "romaji": "kimono", "meaning": "pakaian tradisional (kimono)" },
  { "character": "客", "romaji": "kyaku", "meaning": "tamu, pelanggan" },
  { "character": "急", "romaji": "kyuu", "meaning": "tiba-tiba, mendesak" },
  { "character": "急行", "romaji": "kyuukou", "meaning": "kereta ekspres" },
  { "character": "教育", "romaji": "kyouiku", "meaning": "pendidikan" },
  { "character": "教会", "romaji": "kyoukai", "meaning": "gereja" },
  { "character": "競争", "romaji": "kyousou", "meaning": "persaingan, kompetisi" },
  { "character": "興味", "romaji": "kyoumi", "meaning": "minat, ketertarikan" },
  { "character": "近所", "romaji": "kinjo", "meaning": "tetangga, lingkungan sekitar" },
  { "character": "具合", "romaji": "guai", "meaning": "kondisi" },
  { "character": "空気", "romaji": "kuuki", "meaning": "udara" },
  { "character": "空港", "romaji": "kuukou", "meaning": "bandara" },
  { "character": "草", "romaji": "kusa", "meaning": "rumput" },
  { "character": "くださる", "romaji": "kudasaru", "meaning": "memberikan (hormat)" },
  { "character": "首", "romaji": "kubi", "meaning": "leher" },
  { "character": "雲", "romaji": "kumo", "meaning": "awan" },
  { "character": "比べる", "romaji": "kuraberu", "meaning": "membandingkan" },
  { "character": "くれる", "romaji": "kureru", "meaning": "memberikan (kepadaku)" },
  { "character": "暮れる", "romaji": "kureru", "meaning": "menjadi gelap, berakhir (hari/tahun)" },
  { "character": "黒い", "romaji": "kuroi", "meaning": "hitam" },
  { "character": "君", "romaji": "-kun", "meaning": "sufiks untuk laki-laki" },
  { "character": "毛", "romaji": "ke", "meaning": "bulu, rambut" },
  { "character": "経済", "romaji": "keizai", "meaning": "ekonomi" },
  { "character": "警察", "romaji": "keisatsu", "meaning": "polisi" },
  { "character": "景色", "romaji": "keshiki", "meaning": "pemandangan" },
  { "character": "消しゴム", "romaji": "keshigomu", "meaning": "penghapus" },
  { "character": "下宿", "romaji": "geshuku", "meaning": "indekos" },
  { "character": "決して", "romaji": "kesshite", "meaning": "sama sekali tidak" },
  { "character": "けれど", "romaji": "keredo", "meaning": "tetapi" },
  { "character": "原因", "romaji": "gen'in", "meaning": "penyebab" },
  { "character": "けんか", "romaji": "kenka", "meaning": "pertengkaran" },
  { "character": "研究", "romaji": "kenkyuu", "meaning": "penelitian" },
  { "character": "研究室", "romaji": "kenkyuushitsu", "meaning": "ruang penelitian, laboratorium" },
  { "character": "見物", "romaji": "kenbutsu", "meaning": "berkeliling melihat-lihat" },
  { "character": "子", "romaji": "ko", "meaning": "anak" },
  { "character": "こう", "romaji": "kou", "meaning": "begini" },
  { "character": "郊外", "romaji": "kougai", "meaning": "pinggiran kota" },
  { "character": "講義", "romaji": "kougi", "meaning": "kuliah" },
  { "character": "工業", "romaji": "kougyou", "meaning": "industri" },
  { "character": "高校", "romaji": "koukou", "meaning": "SMA" },
  { "character": "高校生", "romaji": "koukousei", "meaning": "siswa SMA" },
  { "character": "工場", "romaji": "koujou", "meaning": "pabrik" },
  { "character": "校長", "romaji": "kouchou", "meaning": "kepala sekolah" },
  { "character": "交通", "romaji": "koutsuu", "meaning": "lalu lintas, transportasi" },
  { "character": "講堂", "romaji": "koudou", "meaning": "auditorium" },
  { "character": "高等学校", "romaji": "koutougakkou", "meaning": "Sekolah Menengah Atas" },
  { "character": "公務員", "romaji": "koumuin", "meaning": "pegawai negeri" },
  { "character": "国際", "romaji": "kokusai", "meaning": "internasional" },
  { "character": "心", "romaji": "kokoro", "meaning": "hati, pikiran" },
  { "character": "ご主人", "romaji": "goshujin", "meaning": "suami (orang lain)" },
  { "character": "故障", "romaji": "koshou", "meaning": "kerusakan" },
  { "character": "ご存知", "romaji": "gozonji", "meaning": "tahu (hormat)" },
  { "character": "答", "romaji": "kotae", "meaning": "jawaban" },
  { "character": "ごちそう", "romaji": "gochisou", "meaning": "jamuan makan" },
  { "character": "事", "romaji": "koto", "meaning": "hal, perkara" },
  { "character": "小鳥", "romaji": "kotori", "meaning": "burung kecil" },
  { "character": "この間", "romaji": "konoaida", "meaning": "baru-baru ini" },
  { "character": "この頃", "romaji": "konogoro", "meaning": "akhir-akhir ini" },
  { "character": "細かい", "romaji": "komakai", "meaning": "kecil, rinci" },
  { "character": "ごみ", "romaji": "gomi", "meaning": "sampah" },
  { "character": "込む", "romaji": "komu", "meaning": "padat, ramai" },
  { "character": "米", "romaji": "kome", "meaning": "beras" },
  { "character": "ごらんになる", "romaji": "goran ni naru", "meaning": "melihat (hormat)" },
  { "character": "これから", "romaji": "korekara", "meaning": "mulai sekarang" },
  { "character": "怖い", "romaji": "kowai", "meaning": "takut, menakutkan" },
  { "character": "壊す", "romaji": "kowasu", "meaning": "merusak" },
  { "character": "壊れる", "romaji": "kowareru", "meaning": "rusak" },
  { "character": "今度", "romaji": "kondo", "meaning": "kali ini, lain kali" },
  { "character": "今夜", "romaji": "kon'ya", "meaning": "malam ini" },
  { "character": "最近", "romaji": "saikin", "meaning": "akhir-akhir ini" },
  { "character": "最後", "romaji": "saigo", "meaning": "terakhir" },
  { "character": "最初", "romaji": "saisho", "meaning": "pertama, awal" },
  { "character": "坂", "romaji": "saka", "meaning": "tanjakan" },
  { "character": "探す", "romaji": "sagasu", "meaning": "mencari" },
  { "character": "下がる", "romaji": "sagaru", "meaning": "turun" },
  { "character": "下げる", "romaji": "sageru", "meaning": "menurunkan" },
  { "character": "盛ん", "romaji": "sakan", "meaning": "populer, makmur" },
  { "character": "下げる", "romaji": "sageru", "meaning": "menurunkan" },
  { "character": "差し上げる", "romaji": "sashiageru", "meaning": "memberikan (merendahkan diri)" },
  { "character": "さっき", "romaji": "sakki", "meaning": "tadi" },
  { "character": "寂しい", "romaji": "sabishii", "meaning": "kesepian" },
  { "character": "さ来月", "romaji": "saraigetsu", "meaning": "dua bulan lagi" },
  { "character": "さ来週", "romaji": "saraishuu", "meaning": "dua minggu lagi" },
  { "character": "騒ぐ", "romaji": "sawagu", "meaning": "membuat keributan" },
  { "character": "触る", "romaji": "sawaru", "meaning": "menyentuh" },
  { "character": "産業", "romaji": "sangyou", "meaning": "industri" },
  { "character": "残念", "romaji": "zannen", "meaning": "sayang sekali" },
  { "character": "市", "romaji": "shi", "meaning": "kota" },
  { "character": "字", "romaji": "ji", "meaning": "huruf" },
  { "character": "試合", "romaji": "shiai", "meaning": "pertandingan" },
  { "character": "仕方", "romaji": "shikata", "meaning": "cara melakukan" },
  { "character": "試験", "romaji": "shiken", "meaning": "ujian" },
  { "character": "事故", "romaji": "jiko", "meaning": "kecelakaan" },
  { "character": "地震", "romaji": "jishin", "meaning": "gempa bumi" },
  { "character": "時代", "romaji": "jidai", "meaning": "zaman, era" },
  { "character": "下着", "romaji": "shitagi", "meaning": "pakaian dalam" },
  { "character": "しっかり", "romaji": "shikkari", "meaning": "dengan kuat, sungguh-sungguh" },
  { "character": "失敗", "romaji": "shippai", "meaning": "kegagalan" },
  { "character": "辞典", "romaji": "jiten", "meaning": "kamus" },
  { "character": "品物", "romaji": "shinamono", "meaning": "barang dagangan" },
  { "character": "しばらく", "romaji": "shibaraku", "meaning": "sejenak" },
  { "character": "島", "romaji": "shima", "meaning": "pulau" },
  { "character": "市民", "romaji": "shimin", "meaning": "warga kota" },
  { "character": "事務所", "romaji": "jimusho", "meaning": "kantor" },
  { "character": "社会", "romaji": "shakai", "meaning": "masyarakat" },
  { "character": "社長", "romaji": "shachou", "meaning": "direktur utama" },
  { "character": "邪魔", "romaji": "jama", "meaning": "gangguan" },
  { "character": "ジャム", "romaji": "jamu", "meaning": "selai" },
  { "character": "自由", "romaji": "jiyuu", "meaning": "bebas" },
  { "character": "習慣", "romaji": "shuukan", "meaning": "kebiasaan" },
  { "character": "住所", "romaji": "juusho", "meaning": "alamat" },
  { "character": "十分", "romaji": "juubun", "meaning": "cukup" },
  { "character": "趣味", "romaji": "shumi", "meaning": "hobi" },
  { "character": "紹介", "romaji": "shoukai", "meaning": "perkenalan" },
  { "character": "小学校", "romaji": "shougakkou", "meaning": "SD" },
  { "character": "小説", "romaji": "shousetsu", "meaning": "novel" },
  { "character": "将来", "romaji": "shourai", "meaning": "masa depan" },
  { "character": "食料品", "romaji": "shokuryouhin", "meaning": "bahan makanan" },
  { "character": "女性", "romaji": "josei", "meaning": "wanita" },
  { "character": "知らせる", "romaji": "shiraseru", "meaning": "memberitahukan" },
  { "character": "調べる", "romaji": "shiraberu", "meaning": "memeriksa, mencari tahu" },
  { "character": "人口", "romaji": "jinkou", "meaning": "populasi penduduk" },
  { "character": "神社", "romaji": "jinja", "meaning": "kuil Shinto" },
  { "character": "親切", "romaji": "shinsetsu", "meaning": "baik hati" },
  { "character": "心配", "romaji": "shinpai", "meaning": "khawatir" },
  { "character": "新聞社", "romaji": "shinbunsha", "meaning": "perusahaan koran" },
  { "character": "水泳", "romaji": "suiei", "meaning": "renang" },
  { "character": "水道", "romaji": "suidou", "meaning": "saluran air" },
  { "character": "ずいぶん", "romaji": "zuibun", "meaning": "sangat, luar biasa" },
  { "character": "数学", "romaji": "suugaku", "meaning": "matematika" },
  { "character": "スーツ", "romaji": "suutsu", "meaning": "jas" },
  { "character": "スーツケース", "romaji": "suutsukeesu", "meaning": "koper" },
  { "character": "過ぎる", "romaji": "sugiru", "meaning": "melewati, terlalu" },
  { "character": "すく", "romaji": "suku", "meaning": "menjadi kosong (perut)" },
  { "character": "すごい", "romaji": "sugoi", "meaning": "hebat" },
  { "character": "進む", "romaji": "susumu", "meaning": "maju" },
  { "character": "すっかり", "romaji": "sukkari", "meaning": "sepenuhnya" },
  { "character": "ずっと", "romaji": "zutto", "meaning": "terus menerus, jauh lebih" },
  { "character": "捨てる", "romaji": "suteru", "meaning": "membuang" },
  { "character": "すり", "romaji": "suri", "meaning": "pencopet" },
  { "character": "すると", "romaji": "suruto", "meaning": "lalu, kemudian" },
  { "character": "生産", "romaji": "seisan", "meaning": "produksi" },
  { "character": "政治", "romaji": "seiji", "meaning": "politik" },
  { "character": "西洋", "romaji": "seiyou", "meaning": "Barat" },
  { "character": "世界", "romaji": "sekai", "meaning": "dunia" },
  { "character": "席", "romaji": "seki", "meaning": "tempat duduk" },
  { "character": "説明", "romaji": "setsumei", "meaning": "penjelasan" },
  { "character": "背中", "romaji": "senaka", "meaning": "punggung" },
  { "character": "ぜひ", "romaji": "zehi", "meaning": "pasti, dengan segala cara" },
  { "character": "世話", "romaji": "sewa", "meaning": "perawatan, urusan" },
  { "character": "線", "romaji": "sen", "meaning": "garis" },
  { "character": "全然", "romaji": "zenzen", "meaning": "sama sekali tidak" },
  { "character": "戦争", "romaji": "sensou", "meaning": "perang" },
  { "character": "先輩", "romaji": "senpai", "meaning": "senior" },
  { "character": "そう", "romaji": "sou", "meaning": "begitu" },
  { "character": "相談", "romaji": "soudan", "meaning": "konsultasi" },
  { "character": "育てる", "romaji": "sodateru", "meaning": "membesarkan, mendidik" },
  { "character": "卒業", "romaji": "sotsugyou", "meaning": "kelulusan" },
  { "character": "祖父", "romaji": "sofu", "meaning": "kakek" },
  { "character": "ソフト", "romaji": "sofuto", "meaning": "perangkat lunak" },
  { "character": "祖母", "romaji": "sobo", "meaning": "nenek" },
  { "character": "それで", "romaji": "sorede", "meaning": "karena itu" },
  { "character": "それに", "romaji": "soreni", "meaning": "selain itu" },
  { "character": "それほど", "romaji": "sorehodo", "meaning": "tidak sebegitu" },
  { "character": "そろそろ", "romaji": "sorosoro", "meaning": "sebentar lagi, perlahan-lahan" },
  { "character": "そんな", "romaji": "sonna", "meaning": "seperti itu" },
  { "character": "そんなに", "romaji": "sonnani", "meaning": "sebegenitunya" },
  { "character": "退院", "romaji": "taiin", "meaning": "keluar rumah sakit" },
  { "character": "大学生", "romaji": "daigakusei", "meaning": "mahasiswa" },
  { "character": "大事", "romaji": "daiji", "meaning": "penting" },
  { "character": "大体", "romaji": "daitai", "meaning": "hampir, secara umum" },
  { "character": "たいてい", "romaji": "taitei", "meaning": "biasanya" },
  { "character": "タイプ", "romaji": "taipu", "meaning": "tipe" },
  { "character": "大分", "romaji": "daibu", "meaning": "sangat banyak, sebagian besar" },
  { "character": "台風", "romaji": "taifuu", "meaning": "angin topan" },
  { "character": "倒れる", "romaji": "taoreru", "meaning": "rubuh, jatuh" },
  { "character": "だから", "romaji": "dakara", "meaning": "oleh karena itu" },
  { "character": "確か", "romaji": "tashika", "meaning": "pasti, kalau tidak salah" },
  { "character": "足す", "romaji": "tasu", "meaning": "menambah" },
  { "character": "尋ねる", "romaji": "tazuneru", "meaning": "bertanya, mengunjungi" },
  { "character": "正しい", "romaji": "tadashii", "meaning": "benar" },
  { "character": "畳", "romaji": "tatami", "meaning": "tikar Jepang (tatami)" },
  { "character": "立てる", "romaji": "tateru", "meaning": "mendirikan" },
  { "character": "建てる", "romaji": "tateru", "meaning": "membangun" },
  { "character": "例えば", "romaji": "tatoeba", "meaning": "misalnya" },
  { "character": "棚", "romaji": "tana", "meaning": "rak" },
  { "character": "楽しみ", "romaji": "tanoshimi", "meaning": "kesenangan, menantikan" },
  { "character": "楽しむ", "romaji": "tanoshimu", "meaning": "menikmati" },
  { "character": "たまに", "romaji": "tamani", "meaning": "terkadang" },
  { "character": "為", "romaji": "tame", "meaning": "demi, untuk" },
  { "character": "だめ", "romaji": "dame", "meaning": "tidak boleh, tidak berguna" },
  { "character": "足りる", "romaji": "tariru", "meaning": "cukup" },
  { "character": "男性", "romaji": "dansei", "meaning": "pria" },
  { "character": "暖房", "romaji": "danbou", "meaning": "pemanas ruangan" },
  { "character": "血", "romaji": "chi", "meaning": "darah" },
  { "character": "チェックする", "romaji": "chekku suru", "meaning": "memeriksa" },
  { "character": "力", "romaji": "chikara", "meaning": "kekuatan" },
  { "character": "ちっとも", "romaji": "chittomo", "meaning": "sama sekali tidak" },
  { "character": "ちゃん", "romaji": "-chan", "meaning": "sufiks untuk anak/akrab" },
  { "character": "注意", "romaji": "chuui", "meaning": "perhatian, peringatan" },
  { "character": "中学校", "romaji": "chuugakkou", "meaning": "SMP" },
  { "character": "注射", "romaji": "chuusha", "meaning": "suntikan" },
  { "character": "駐車場", "romaji": "chuushajou", "meaning": "tempat parkir" },
  { "character": "地理", "romaji": "chiri", "meaning": "geografi" },
  { "character": "捕まえる", "romaji": "tsukamaeru", "meaning": "menangkap" },
  { "character": "月", "romaji": "tsuki", "meaning": "bulan" },
  { "character": "付く", "romaji": "tsuku", "meaning": "melekat, menempel" },
  { "character": "漬ける", "romaji": "tsukeru", "meaning": "merendam, mengawetkan" },
  { "character": "都合", "romaji": "tsugou", "meaning": "kondisi, jadwal" },
  { "character": "伝える", "romaji": "tsutaeru", "meaning": "menyampaikan" },
  { "character": "続く", "romaji": "tsuduku", "meaning": "berlanjut" },
  { "character": "続ける", "romaji": "tsudukeru", "meaning": "melanjutkan" },
  { "character": "包む", "romaji": "tsutsumu", "meaning": "membungkus" },
  { "character": "妻", "romaji": "tsuma", "meaning": "istri" },
  { "character": "つもり", "romaji": "tsumori", "meaning": "berniat" },
  { "character": "釣る", "romaji": "tsuru", "meaning": "memancing" },
  { "character": "連れる", "romaji": "tsureru", "meaning": "membawa (orang/hewan)" },
  { "character": "丁寧", "romaji": "teinei", "meaning": "sopan, hati-hati" },
  { "character": "テキスト", "romaji": "tekisuto", "meaning": "buku teks" },
  { "character": "適当", "romaji": "tekitou", "meaning": "pantas, sesuai" },
  { "character": "できるだけ", "romaji": "dekiru dake", "meaning": "sebisa mungkin" },
  { "character": "手伝う", "romaji": "tetsudau", "meaning": "membantu" },
  { "character": "テニス", "romaji": "tenisu", "meaning": "tenis" },
  { "character": "手袋", "romaji": "tebukuro", "meaning": "sarung tangan" },
  { "character": "寺", "romaji": "tera", "meaning": "kuil Buddha" },
  { "character": "点", "romaji": "ten", "meaning": "titik, skor" },
  { "character": "店員", "romaji": "ten'in", "meaning": "pegawai toko" },
  { "character": "天気予報", "romaji": "tenkiyohou", "meaning": "prakiraan cuaca" },
  { "character": "電灯", "romaji": "dentou", "meaning": "lampu listrik" },
  { "character": "電報", "romaji": "denpou", "meaning": "telegram" },
  { "character": "展覧会", "romaji": "tenrankai", "meaning": "pameran" },
  { "character": "都", "romaji": "to", "meaning": "ibukota" },
  { "character": "道具", "romaji": "dougu", "meaning": "alat" },
  { "character": "とうとう", "romaji": "toutou", "meaning": "akhirnya" },
  { "character": "動物園", "romaji": "doubutsuen", "meaning": "kebun binatang" },
  { "character": "遠く", "romaji": "tooku", "meaning": "jauh" },
  { "character": "通り", "romaji": "toori", "meaning": "jalan" },
  { "character": "通る", "romaji": "tooru", "meaning": "lewat" },
  { "character": "特に", "romaji": "tokuni", "meaning": "terutama" },
  { "character": "特別", "romaji": "tokubetsu", "meaning": "spesial" },
  { "character": "床屋", "romaji": "tokoya", "meaning": "tukang cukur" },
  { "character": "途中", "romaji": "tochuu", "meaning": "di tengah jalan" },
  { "character": "特急", "romaji": "tokkyuu", "meaning": "kereta ekspres terbatas" },
  { "character": "届ける", "romaji": "todokeru", "meaning": "mengantarkan" },
  { "character": "泊まる", "romaji": "tomaru", "meaning": "menginap" },
  { "character": "止める", "romaji": "tomeru", "meaning": "menghentikan" },
  { "character": "取り替える", "romaji": "torikaeru", "meaning": "menukar, mengganti" },
  { "character": "泥棒", "romaji": "dorobou", "meaning": "pencuri" },
  { "character": "どんどん", "romaji": "dondon", "meaning": "semakin" },
  { "character": "直す", "romaji": "naosu", "meaning": "memperbaiki" },
  { "character": "直る", "romaji": "naoru", "meaning": "diperbaiki, sembuh" },
  { "character": "治る", "romaji": "naoru", "meaning": "sembuh (dari penyakit)" },
  { "character": "泣く", "romaji": "naku", "meaning": "menangis" },
  { "character": "無くなる", "romaji": "nakunaru", "meaning": "hilang, habis" },
  { "character": "亡くなる", "romaji": "nakunaru", "meaning": "meninggal dunia" },
  { "character": "投げる", "romaji": "nageru", "meaning": "melempar" },
  { "character": "なさる", "romaji": "nasaru", "meaning": "melakukan (hormat)" },
  { "character": "鳴る", "romaji": "naru", "meaning": "berbunyi" },
  { "character": "なるべく", "romaji": "narubeku", "meaning": "sebisa mungkin" },
  { "character": "なるほど", "romaji": "naruhodo", "meaning": "memang benar, oh begitu" },
  { "character": "慣れる", "romaji": "nareru", "meaning": "terbiasa" },
  { "character": "匂い", "romaji": "nioi", "meaning": "bau, aroma" },
  { "character": "苦い", "romaji": "nigai", "meaning": "pahit" },
  { "character": "逃げる", "romaji": "nigeru", "meaning": "melarikan diri" },
  { "character": "日記", "romaji": "nikki", "meaning": "buku harian" },
  { "character": "入院", "romaji": "nyuuin", "meaning": "masuk rumah sakit" },
  { "character": "入学", "romaji": "nyuugaku", "meaning": "masuk sekolah" },
  { "character": "似る", "romaji": "niru", "meaning": "mirip" },
  { "character": "人形", "romaji": "ningyou", "meaning": "boneka" },
  { "character": "盗む", "romaji": "nusumu", "meaning": "mencuri" },
  { "character": "塗る", "romaji": "nuru", "meaning": "mengoles, mengecat" },
  { "character": "ぬれる", "romaji": "nureru", "meaning": "basah" },
  { "character": "ねだん", "romaji": "nedan", "meaning": "harga" },
  { "character": "熱", "romaji": "netsu", "meaning": "demam, panas" },
  { "character": "熱心", "romaji": "nesshin", "meaning": "tekun, antusias" },
  { "character": "寝坊", "romaji": "nebou", "meaning": "bangun kesiangan" },
  { "character": "眠い", "romaji": "nemui", "meaning": "mengantuk" },
  { "character": "眠る", "romaji": "nemuru", "meaning": "tidur" },
  { "character": "残る", "romaji": "nokoru", "meaning": "tersisa" },
  { "character": "乗り換える", "romaji": "norikaeru", "meaning": "pindah kendaraan" },
  { "character": "乗り物", "romaji": "norimono", "meaning": "kendaraan" },
  { "character": "葉", "romaji": "ha", "meaning": "daun" },
  { "character": "場合", "romaji": "baai", "meaning": "kasus, jika" },
  { "character": "倍", "romaji": "bai", "meaning": "kali lipat" },
  { "character": "拝見する", "romaji": "haiken suru", "meaning": "melihat (merendahkan diri)" },
  { "character": "歯医者", "romaji": "haisha", "meaning": "dokter gigi" },
  { "character": "運ぶ", "romaji": "hakobu", "meaning": "mengangkut, membawa" },
  { "character": "始める", "romaji": "hajimeru", "meaning": "memulai" },
  { "character": "場所", "romaji": "basho", "meaning": "tempat" },
  { "character": "はず", "romaji": "hazu", "meaning": "seharusnya" },
  { "character": "恥ずかしい", "romaji": "hazukashii", "meaning": "malu" },
  { "character": "発音", "romaji": "hatsuon", "meaning": "pelafalan" },
  { "character": "はっきり", "romaji": "hakkiri", "meaning": "dengan jelas" },
  { "character": "花見", "romaji": "hanami", "meaning": "melihat bunga sakura" },
  { "character": "林", "romaji": "hayashi", "meaning": "hutan kecil" },
  { "character": "払う", "romaji": "harau", "meaning": "membayar" },
  { "character": "番組", "romaji": "bangumi", "meaning": "program TV" },
  { "character": "反対", "romaji": "hantai", "meaning": "berlawanan, menentang" },
  { "character": "日", "romaji": "hi", "meaning": "hari, matahari" },
  { "character": "火", "romaji": "hi", "meaning": "api" },
  { "character": "冷える", "romaji": "hieru", "meaning": "menjadi dingin" },
  { "character": "光", "romaji": "hikari", "meaning": "cahaya" },
  { "character": "光る", "romaji": "hikaru", "meaning": "bersinar" },
  { "character": "引き出し", "romaji": "hikidashi", "meaning": "laci" },
  { "character": "引き出す", "romaji": "hikidasu", "meaning": "menarik keluar" },
  { "character": "ひげ", "romaji": "hige", "meaning": "kumis, jenggot" },
  { "character": "飛行場", "romaji": "hikoujou", "meaning": "bandara" },
  { "character": "久しぶり", "romaji": "hisashiburi", "meaning": "sudah lama tidak bertemu" },
  { "character": "美術館", "romaji": "bijutsukan", "meaning": "museum seni" },
  { "character": "非常に", "romaji": "hijouni", "meaning": "sangat" },
  { "character": "びっくりする", "romaji": "bikkuri suru", "meaning": "terkejut" },
  { "character": "引っ越す", "romaji": "hikkosu", "meaning": "pindah rumah" },
  { "character": "必要", "romaji": "hitsuyou", "meaning": "perlu" },
  { "character": "ひどい", "romaji": "hidoi", "meaning": "kejam, parah" },
  { "character": "開く", "romaji": "hiraku", "meaning": "membuka" },
  { "character": "昼間", "romaji": "hiruma", "meaning": "siang hari" },
  { "character": "昼休み", "romaji": "hiruyasumi", "meaning": "istirahat siang" },
  { "character": "拾う", "romaji": "hirou", "meaning": "memungut" },
  { "character": "増える", "romaji": "fueru", "meaning": "bertambah" },
  { "character": "深い", "romaji": "fukai", "meaning": "dalam" },
  { "character": "複雑", "romaji": "fukuzatsu", "meaning": "rumit" },
  { "character": "吹く", "romaji": "fuku", "meaning": "bertiup" },
  { "character": "復習", "romaji": "fukushuu", "meaning": "mengulang pelajaran" },
  { "character": "部長", "romaji": "buchou", "meaning": "manajer" },
  { "character": "普通", "romaji": "futsuu", "meaning": "biasanya, umum" },
  { "character": "ぶどう", "romaji": "budou", "meaning": "anggur" },
  { "character": "太る", "romaji": "futoru", "meaning": "menjadi gemuk" },
  { "character": "布団", "romaji": "futon", "meaning": "kasur lipat (futon)" },
  { "character": "舟", "romaji": "fune", "meaning": "perahu" },
  { "character": "不便", "romaji": "fuben", "meaning": "tidak praktis" },
  { "character": "踏む", "romaji": "fumu", "meaning": "menginjak" },
  { "character": "降り出す", "romaji": "furidasu", "meaning": "mulai turun hujan" },
  { "character": "プレゼント", "romaji": "purezento", "meaning": "hadiah" },
  { "character": "文化", "romaji": "bunka", "meaning": "budaya" },
  { "character": "文学", "romaji": "bungaku", "meaning": "sastra" },
  { "character": "文法", "romaji": "bunpou", "meaning": "tata bahasa" },
  { "character": "別", "romaji": "betsu", "meaning": "terpisah, lain" },
  { "character": "変", "romaji": "hen", "meaning": "aneh" },
  { "character": "返事", "romaji": "henji", "meaning": "balasan, jawaban" },
  { "character": "貿易", "romaji": "boueki", "meaning": "perdagangan internasional" },
  { "character": "法律", "romaji": "houritsu", "meaning": "hukum" },
  { "character": "僕", "romaji": "boku", "meaning": "aku (laki-laki)" },
  { "character": "星", "romaji": "hoshi", "meaning": "bintang" },
  { "character": "ほど", "romaji": "hodo", "meaning": "sekitar, sejauh" },
  { "character": "ほとんど", "romaji": "hotondo", "meaning": "hampir semuanya" },
  { "character": "褒める", "romaji": "homeru", "meaning": "memuji" },
  { "character": "翻訳", "romaji": "hon'yaku", "meaning": "terjemahan" },
  { "character": "参る", "romaji": "mairu", "meaning": "datang, pergi (merendahkan diri)" },
  { "character": "負ける", "romaji": "makeru", "meaning": "kalah" },
  { "character": "真面目", "romaji": "majime", "meaning": "serius, rajin" },
  { "character": "間違える", "romaji": "machigaeru", "meaning": "berbuat salah" },
  { "character": "間に合う", "romaji": "maniau", "meaning": "tepat waktu" },
  { "character": "周り", "romaji": "mawari", "meaning": "sekitar" },
  { "character": "回る", "romaji": "mawaru", "meaning": "berputar" },
  { "character": "漫画", "romaji": "manga", "meaning": "komik jepang" },
  { "character": "真ん中", "romaji": "mannaka", "meaning": "tepat di tengah" },
  { "character": "見える", "romaji": "mieru", "meaning": "terlihat" },
  { "character": "湖", "romaji": "mizuumi", "meaning": "danau" },
  { "character": "味噌", "romaji": "miso", "meaning": "kedelai fermentasi (miso)" },
  { "character": "見つかる", "romaji": "mitsukaru", "meaning": "ditemukan" },
  { "character": "見つける", "romaji": "mitsukeru", "meaning": "menemukan" },
  { "character": "皆", "romaji": "mina", "meaning": "semua orang" },
  { "character": "港", "romaji": "minato", "meaning": "pelabuhan" },
  { "character": "向かう", "romaji": "mukau", "meaning": "menghadap, menuju" },
  { "character": "迎える", "romaji": "mukaeru", "meaning": "menjemput, menyambut" },
  { "character": "昔", "romaji": "mukashi", "meaning": "zaman dahulu" },
  { "character": "虫", "romaji": "mushi", "meaning": "serangga" },
  { "character": "息子", "romaji": "musuko", "meaning": "anak laki-laki" },
  { "character": "娘", "romaji": "musume", "meaning": "anak perempuan" },
  { "character": "無理", "romaji": "muri", "meaning": "mustahil" },
  { "character": "召し上がる", "romaji": "meshiagaru", "meaning": "makan, minum (hormat)" },
  { "character": "珍しい", "romaji": "mezurashii", "meaning": "langka" },
  { "character": "申し上げる", "romaji": "moushiageru", "meaning": "mengatakan (merendahkan diri)" },
  { "character": "申す", "romaji": "mousu", "meaning": "bernama, berkata (merendahkan diri)" },
  { "character": "もし", "romaji": "moshi", "meaning": "jika" },
  { "character": "戻る", "romaji": "modoru", "meaning": "kembali" },
  { "character": "木綿", "romaji": "momen", "meaning": "kapas" },
  { "character": "森", "romaji": "mori", "meaning": "hutan" },
  { "character": "焼く", "romaji": "yaku", "meaning": "memanggang" },
  { "character": "約束", "romaji": "yakusoku", "meaning": "janji" },
  { "character": "役に立つ", "romaji": "yaku ni tatsu", "meaning": "berguna" },
  { "character": "焼ける", "romaji": "yakeru", "meaning": "terbakar, terpanggang" },
  { "character": "優しい", "romaji": "yasashii", "meaning": "baik hati, lembut" },
  { "character": "痩せる", "romaji": "yaseru", "meaning": "menjadi kurus" },
  { "character": "やっと", "romaji": "yatto", "meaning": "akhirnya" },
  { "character": "止む", "romaji": "yamu", "meaning": "berhenti (hujan)" },
  { "character": "辞める", "romaji": "yameru", "meaning": "berhenti, resign" },
  { "character": "柔らかい", "romaji": "yawarakai", "meaning": "lembut, empuk" },
  { "character": "湯", "romaji": "yu", "meaning": "air panas" },
  { "character": "指", "romaji": "yubi", "meaning": "jari" },
  { "character": "指輪", "romaji": "yubiwa", "meaning": "cincin" },
  { "character": "夢", "romaji": "yume", "meaning": "mimpi" },
  { "character": "揺れる", "romaji": "yureru", "meaning": "bergoyang" },
  { "character": "用", "romaji": "you", "meaning": "urusan" },
  { "character": "用意", "romaji": "youi", "meaning": "persiapan" },
  { "character": "用事", "romaji": "youji", "meaning": "urusan, keperluan" },
  { "character": "汚れる", "romaji": "yogoreru", "meaning": "menjadi kotor" },
  { "character": "予習", "romaji": "yoshuu", "meaning": "persiapan belajar" },
  { "character": "予定", "romaji": "yotei", "meaning": "jadwal" },
  { "character": "予約", "romaji": "yoyaku", "meaning": "reservasi" },
  { "character": "寄る", "romaji": "yoru", "meaning": "mampir" },
  { "character": "喜ぶ", "romaji": "yorokobu", "meaning": "bergembira" },
  { "character": "理由", "romaji": "riyuu", "meaning": "alasan" },
  { "character": "利用", "romaji": "riyou", "meaning": "pemanfaatan, penggunaan" },
  { "character": "両方", "romaji": "ryouhou", "meaning": "keduanya" },
  { "character": "旅館", "romaji": "ryokan", "meaning": "penginapan tradisional" },
  { "character": "留守", "romaji": "rusu", "meaning": "sedang tidak ada di rumah" },
  { "character": "歴史", "romaji": "rekishi", "meaning": "sejarah" },
  { "character": "連絡", "romaji": "renraku", "meaning": "kontak, hubungi" },
  { "character": "沸かす", "romaji": "wakasu", "meaning": "mendidihkan air" },
  { "character": "別れる", "romaji": "wakareru", "meaning": "berpisah" },
  { "character": "沸く", "romaji": "waku", "meaning": "mendidih" },
  { "character": "訳", "romaji": "wake", "meaning": "alasan, makna" },
  { "character": "忘れ物", "romaji": "wasuremono", "meaning": "barang yang tertinggal" },
  { "character": "笑う", "romaji": "warau", "meaning": "tertawa" },
  { "character": "割合", "romaji": "wariai", "meaning": "persentase, lumayan" },
  { "character": "割れる", "romaji": "wareru", "meaning": "pecah" }
];

charactersData.vocabulary_n4 = realN4Vocab;

fs.writeFileSync(charactersFile, JSON.stringify(charactersData, null, 2));
console.log(`Successfully replaced vocabulary_n4 with ${realN4Vocab.length} authentic JLPT N4 words.`);
