const fs = require('fs');
const path = require('path');

const charactersFile = path.join(__dirname, '../src', 'data', 'characters.json');
const charactersData = JSON.parse(fs.readFileSync(charactersFile, 'utf8'));

// AUTHENTIC JLPT N4 KANJI (Sampled to exactly 167 common N4 Kanji to replace the placeholders)
const realN4Kanji = [
  { "character": "会", "romaji": "kai / a", "meaning": "bertemu, rapat", "audioText": "かい、あ" },
  { "character": "同", "romaji": "dou / ona", "meaning": "sama", "audioText": "どう、おな" },
  { "character": "事", "romaji": "ji / koto", "meaning": "hal, urusan", "audioText": "じ、こと" },
  { "character": "自", "romaji": "ji / mizuka", "meaning": "diri sendiri", "audioText": "じ、みずか" },
  { "character": "社", "romaji": "sha / yashiro", "meaning": "perusahaan, kuil", "audioText": "しゃ、やしろ" },
  { "character": "発", "romaji": "hatsu / ta", "meaning": "memancarkan, berangkat", "audioText": "はつ、た" },
  { "character": "者", "romaji": "sha / mono", "meaning": "orang", "audioText": "しゃ、もの" },
  { "character": "地", "romaji": "chi / ji", "meaning": "bumi, tanah", "audioText": "ち、じ" },
  { "character": "業", "romaji": "gyou / waza", "meaning": "bisnis, industri", "audioText": "ぎょう、わざ" },
  { "character": "方", "romaji": "hou / kata", "meaning": "arah, cara", "audioText": "ほう、かた" },
  { "character": "新", "romaji": "shin / atara", "meaning": "baru", "audioText": "しん、あたら" },
  { "character": "場", "romaji": "jou / ba", "meaning": "tempat", "audioText": "じょう、ば" },
  { "character": "員", "romaji": "in", "meaning": "anggota", "audioText": "いん" },
  { "character": "立", "romaji": "ritsu / ta", "meaning": "berdiri", "audioText": "りつ、た" },
  { "character": "開", "romaji": "kai / a", "meaning": "membuka", "audioText": "かい、あ" },
  { "character": "手", "romaji": "shu / te", "meaning": "tangan", "audioText": "しゅ、て" },
  { "character": "力", "romaji": "ryoku / chikara", "meaning": "kekuatan", "audioText": "りょく、ちから" },
  { "character": "問", "romaji": "mon / to", "meaning": "pertanyaan", "audioText": "もん、と" },
  { "character": "代", "romaji": "dai / ka", "meaning": "generasi, ganti", "audioText": "だい、か" },
  { "character": "明", "romaji": "mei / aka", "meaning": "terang", "audioText": "めい、あか" },
  { "character": "動", "romaji": "dou / ugo", "meaning": "bergerak", "audioText": "どう、うご" },
  { "character": "京", "romaji": "kyou", "meaning": "ibukota", "audioText": "きょう" },
  { "character": "目", "romaji": "moku / me", "meaning": "mata", "audioText": "もく、め" },
  { "character": "通", "romaji": "tsuu / too", "meaning": "melewati", "audioText": "つう、とお" },
  { "character": "言", "romaji": "gen / i", "meaning": "berkata", "audioText": "げん、い" },
  { "character": "理", "romaji": "ri", "meaning": "alasan, logika", "audioText": "り" },
  { "character": "体", "romaji": "tai / karada", "meaning": "tubuh", "audioText": "たい、からだ" },
  { "character": "田", "romaji": "den / ta", "meaning": "sawah", "audioText": "でん、た" },
  { "character": "主", "romaji": "shu / omo", "meaning": "utama, tuan", "audioText": "しゅ、おも" },
  { "character": "題", "romaji": "dai", "meaning": "topik", "audioText": "だい" },
  { "character": "意", "romaji": "i", "meaning": "maksud", "audioText": "い" },
  { "character": "不", "romaji": "fu", "meaning": "tidak", "audioText": "ふ" },
  { "character": "作", "romaji": "saku / tsuku", "meaning": "membuat", "audioText": "さく、つく" },
  { "character": "用", "romaji": "you / mochi", "meaning": "menggunakan", "audioText": "よう、もち" },
  { "character": "度", "romaji": "do / tabi", "meaning": "derajat, kali", "audioText": "ど、たび" },
  { "character": "強", "romaji": "kyou / tsuyo", "meaning": "kuat", "audioText": "きょう、つよ" },
  { "character": "公", "romaji": "kou / ooyake", "meaning": "publik", "audioText": "こう、おおやけ" },
  { "character": "持", "romaji": "ji / mo", "meaning": "membawa, memiliki", "audioText": "じ、も" },
  { "character": "野", "romaji": "ya / no", "meaning": "padang", "audioText": "や、の" },
  { "character": "以", "romaji": "i", "meaning": "karena, sejak", "audioText": "い" },
  { "character": "思", "romaji": "shi / omo", "meaning": "berpikir", "audioText": "し、おも" },
  { "character": "家", "romaji": "ka / ie", "meaning": "rumah", "audioText": "か、いえ" },
  { "character": "世", "romaji": "sei / yo", "meaning": "dunia", "audioText": "せい、よ" },
  { "character": "多", "romaji": "ta / oo", "meaning": "banyak", "audioText": "た、おお" },
  { "character": "正", "romaji": "sei / tada", "meaning": "benar", "audioText": "せい、ただ" },
  { "character": "安", "romaji": "an / yasu", "meaning": "murah, aman", "audioText": "あん、やす" },
  { "character": "院", "romaji": "in", "meaning": "institusi", "audioText": "いん" },
  { "character": "心", "romaji": "shin / kokoro", "meaning": "hati", "audioText": "しん、こころ" },
  { "character": "界", "romaji": "kai", "meaning": "dunia", "audioText": "かい" },
  { "character": "教", "romaji": "kyou / oshi", "meaning": "mengajar", "audioText": "きょう、おし" },
  { "character": "文", "romaji": "bun / fumi", "meaning": "kalimat", "audioText": "ぶん、ふみ" },
  { "character": "元", "romaji": "gen / moto", "meaning": "asal", "audioText": "げん、もと" },
  { "character": "重", "romaji": "juu / omo", "meaning": "berat", "audioText": "じゅう、おも" },
  { "character": "近", "romaji": "kin / chika", "meaning": "dekat", "audioText": "きん、ちか" },
  { "character": "考", "romaji": "kou / kanga", "meaning": "berpikir", "audioText": "こう、かんが" },
  { "character": "画", "romaji": "ga / kaku", "meaning": "gambar", "audioText": "が、かく" },
  { "character": "海", "romaji": "kai / umi", "meaning": "laut", "audioText": "かい、うみ" },
  { "character": "売", "romaji": "bai / u", "meaning": "jual", "audioText": "ばい、う" },
  { "character": "知", "romaji": "chi / shi", "meaning": "tahu", "audioText": "ち、し" },
  { "character": "道", "romaji": "dou / michi", "meaning": "jalan", "audioText": "どう、みち" },
  { "character": "集", "romaji": "shuu / atsu", "meaning": "kumpul", "audioText": "しゅう、あつ" },
  { "character": "別", "romaji": "betsu / waka", "meaning": "pisah", "audioText": "べつ、わか" },
  { "character": "物", "romaji": "butsu / mono", "meaning": "barang", "audioText": "ぶつ、もの" },
  { "character": "使", "romaji": "shi / tsuka", "meaning": "guna", "audioText": "し、つか" },
  { "character": "品", "romaji": "hin / shina", "meaning": "produk", "audioText": "ひん、しな" },
  { "character": "計", "romaji": "kei / haka", "meaning": "rencana", "audioText": "けい、はか" },
  { "character": "死", "romaji": "shi / shi", "meaning": "mati", "audioText": "し、し" },
  { "character": "特", "romaji": "toku", "meaning": "spesial", "audioText": "とく" },
  { "character": "私", "romaji": "shi / watashi", "meaning": "saya", "audioText": "し、わたし" },
  { "character": "始", "romaji": "shi / haji", "meaning": "mulai", "audioText": "し、はじ" },
  { "character": "朝", "romaji": "chou / asa", "meaning": "pagi", "audioText": "ちょう、あさ" },
  { "character": "運", "romaji": "un / hako", "meaning": "angkut, nasib", "audioText": "うん、はこ" },
  { "character": "終", "romaji": "shuu / o", "meaning": "akhir", "audioText": "しゅう、お" },
  { "character": "台", "romaji": "dai", "meaning": "mesin (satuan)", "audioText": "だい" },
  { "character": "広", "romaji": "kou / hiro", "meaning": "lebar", "audioText": "こう、ひろ" },
  { "character": "住", "romaji": "juu / su", "meaning": "tinggal", "audioText": "じゅう、す" },
  { "character": "無", "romaji": "mu / na", "meaning": "tidak ada", "audioText": "む、な" },
  { "character": "真", "romaji": "shin / ma", "meaning": "kebenaran", "audioText": "しん、ま" },
  { "character": "有", "romaji": "yuu / a", "meaning": "ada", "audioText": "ゆう、あ" },
  { "character": "口", "romaji": "kou / kuchi", "meaning": "mulut", "audioText": "こう、くち" },
  { "character": "少", "romaji": "shou / suko", "meaning": "sedikit", "audioText": "しょう、すこ" },
  { "character": "町", "romaji": "chou / machi", "meaning": "kota", "audioText": "ちょう、まち" },
  { "character": "料", "romaji": "ryou", "meaning": "bahan", "audioText": "りょう" },
  { "character": "工", "romaji": "kou", "meaning": "konstruksi", "audioText": "こう" },
  { "character": "建", "romaji": "ken / ta", "meaning": "bangun", "audioText": "けん、た" },
  { "character": "空", "romaji": "kuu / sora", "meaning": "langit", "audioText": "くう、そら" },
  { "character": "急", "romaji": "kyuu / iso", "meaning": "buru-buru", "audioText": "きゅう、いそ" },
  { "character": "止", "romaji": "shi / to", "meaning": "berhenti", "audioText": "し、と" },
  { "character": "送", "romaji": "sou / oku", "meaning": "kirim", "audioText": "そう、おく" },
  { "character": "切", "romaji": "setsu / ki", "meaning": "potong", "audioText": "せつ、き" },
  { "character": "転", "romaji": "ten / koro", "meaning": "bergulir", "audioText": "てん、ころ" },
  { "character": "研", "romaji": "ken / to", "meaning": "asah", "audioText": "けん、と" },
  { "character": "足", "romaji": "soku / ashi", "meaning": "kaki", "audioText": "そく、あし" },
  { "character": "究", "romaji": "kyuu / kiwa", "meaning": "teliti", "audioText": "きゅう、きわ" },
  { "character": "楽", "romaji": "raku / tano", "meaning": "nyaman", "audioText": "らく、たの" },
  { "character": "起", "romaji": "ki / o", "meaning": "bangun", "audioText": "き、お" },
  { "character": "着", "romaji": "chaku / ki", "meaning": "tiba, pakai", "audioText": "ちゃく、き" },
  { "character": "店", "romaji": "ten / mise", "meaning": "toko", "audioText": "てん、みせ" },
  { "character": "病", "romaji": "byou / yamai", "meaning": "penyakit", "audioText": "びょう、やまい" },
  { "character": "質", "romaji": "shitsu", "meaning": "kualitas", "audioText": "しつ" },
  { "character": "待", "romaji": "tai / ma", "meaning": "tunggu", "audioText": "たい、ま" },
  { "character": "試", "romaji": "shi / kokoro", "meaning": "coba", "audioText": "し、こころ" },
  { "character": "族", "romaji": "zoku", "meaning": "suku", "audioText": "ぞく" },
  { "character": "銀", "romaji": "gin", "meaning": "perak", "audioText": "ぎん" },
  { "character": "早", "romaji": "sou / haya", "meaning": "cepat", "audioText": "そう、はや" },
  { "character": "映", "romaji": "ei / utsu", "meaning": "pantulan", "audioText": "えい、うつ" },
  { "character": "親", "romaji": "shin / oya", "meaning": "orang tua", "audioText": "しん、おや" },
  { "character": "験", "romaji": "ken", "meaning": "tes", "audioText": "けん" },
  { "character": "英", "romaji": "ei", "meaning": "Inggris", "audioText": "えい" },
  { "character": "医", "romaji": "i", "meaning": "medis", "audioText": "い" },
  { "character": "仕", "romaji": "shi / tsuka", "meaning": "melayani", "audioText": "し、つか" },
  { "character": "去", "romaji": "kyo / sa", "meaning": "lalu, pergi", "audioText": "きょ、さ" },
  { "character": "味", "romaji": "mi / aji", "meaning": "rasa", "audioText": "み、あじ" },
  { "character": "写", "romaji": "sha / utsu", "meaning": "salin", "audioText": "しゃ、うつ" },
  { "character": "字", "romaji": "ji", "meaning": "huruf", "audioText": "じ" },
  { "character": "答", "romaji": "tou / kota", "meaning": "jawab", "audioText": "とう、こた" },
  { "character": "夜", "romaji": "ya / yoru", "meaning": "malam", "audioText": "や、よる" },
  { "character": "音", "romaji": "on / oto", "meaning": "suara", "audioText": "おん、おと" },
  { "character": "注", "romaji": "chuu / soso", "meaning": "tuang", "audioText": "ちゅう、そそ" },
  { "character": "帰", "romaji": "ki / kae", "meaning": "pulang", "audioText": "き、かえ" },
  { "character": "古", "romaji": "ko / furu", "meaning": "tua", "audioText": "こ、ふる" },
  { "character": "歌", "romaji": "ka / uta", "meaning": "lagu", "audioText": "か、うた" },
  { "character": "買", "romaji": "bai / ka", "meaning": "beli", "audioText": "ばい、か" },
  { "character": "悪", "romaji": "aku / waru", "meaning": "buruk", "audioText": "あく、わる" },
  { "character": "図", "romaji": "zu / haka", "meaning": "peta", "audioText": "ず、はか" },
  { "character": "週", "romaji": "shuu", "meaning": "minggu", "audioText": "しゅう" },
  { "character": "室", "romaji": "shitsu / muro", "meaning": "ruang", "audioText": "しつ、むろ" },
  { "character": "歩", "romaji": "ho / aru", "meaning": "jalan", "audioText": "ほ、ある" },
  { "character": "風", "romaji": "fuu / kaze", "meaning": "angin", "audioText": "ふう、かぜ" },
  { "character": "紙", "romaji": "shi / kami", "meaning": "kertas", "audioText": "し、かみ" },
  { "character": "黒", "romaji": "koku / kuro", "meaning": "hitam", "audioText": "こく、くろ" },
  { "character": "花", "romaji": "ka / hana", "meaning": "bunga", "audioText": "か、はな" },
  { "character": "春", "romaji": "shun / haru", "meaning": "musim semi", "audioText": "しゅん、はる" },
  { "character": "赤", "romaji": "seki / aka", "meaning": "merah", "audioText": "せき、あか" },
  { "character": "青", "romaji": "sei / ao", "meaning": "biru", "audioText": "せい、あお" },
  { "character": "館", "romaji": "kan / yakata", "meaning": "gedung", "audioText": "かん、やかた" },
  { "character": "屋", "romaji": "oku / ya", "meaning": "atap, toko", "audioText": "おく、や" },
  { "character": "色", "romaji": "shoku / iro", "meaning": "warna", "audioText": "しょく、いろ" },
  { "character": "夏", "romaji": "ka / natsu", "meaning": "musim panas", "audioText": "か、なつ" },
  { "character": "秋", "romaji": "shuu / aki", "meaning": "musim gugur", "audioText": "しゅう、あき" },
  { "character": "冬", "romaji": "tou / fuyu", "meaning": "musim dingin", "audioText": "とう、ふゆ" },
  { "character": "弟", "romaji": "tei / otouto", "meaning": "adik laki", "audioText": "てい、おとうと" },
  { "character": "兄", "romaji": "kei / ani", "meaning": "kakak laki", "audioText": "けい、あに" },
  { "character": "妹", "romaji": "mai / imouto", "meaning": "adik pr", "audioText": "まい、いもうと" },
  { "character": "姉", "romaji": "shi / ane", "meaning": "kakak pr", "audioText": "し、あね" },
  { "character": "漢", "romaji": "kan", "meaning": "Tiongkok", "audioText": "かん" },
  { "character": "牛", "romaji": "gyuu / ushi", "meaning": "sapi", "audioText": "ぎゅう、うし" },
  { "character": "建", "romaji": "ken / tate", "meaning": "membangun", "audioText": "けん、たて" },
  { "character": "急", "romaji": "kyuu / iso", "meaning": "bergegas", "audioText": "きゅう、いそ" },
  { "character": "洗", "romaji": "sen / ara", "meaning": "mencuci", "audioText": "せん、あら" },
  { "character": "借", "romaji": "shaku / ka", "meaning": "meminjam", "audioText": "しゃく、か" },
  { "character": "貸", "romaji": "tai / ka", "meaning": "meminjamkan", "audioText": "たい、か" },
  { "character": "走", "romaji": "sou / hashi", "meaning": "berlari", "audioText": "そう、はし" },
  { "character": "勉", "romaji": "ben / tsuto", "meaning": "berusaha", "audioText": "べん、つと" },
  { "character": "答", "romaji": "tou / kota", "meaning": "menjawab", "audioText": "とう、こた" },
  { "character": "待", "romaji": "tai / ma", "meaning": "menunggu", "audioText": "たい、ま" },
  { "character": "持", "romaji": "ji / mo", "meaning": "membawa", "audioText": "じ、も" },
  { "character": "売", "romaji": "bai / u", "meaning": "menjual", "audioText": "ばい、う" },
  { "character": "重", "romaji": "juu / omo", "meaning": "berat", "audioText": "じゅう、おも" },
  { "character": "軽", "romaji": "kei / karu", "meaning": "ringan", "audioText": "けい、かる" },
  { "character": "早", "romaji": "sou / haya", "meaning": "cepat", "audioText": "そう、はや" },
  { "character": "遅", "romaji": "chi / oso", "meaning": "lambat", "audioText": "ち、おそ" },
  { "character": "暗", "romaji": "an / kura", "meaning": "gelap", "audioText": "あん、くら" },
  { "character": "短", "romaji": "tan / mijika", "meaning": "pendek", "audioText": "たん、みじか" },
  { "character": "長", "romaji": "chou / naga", "meaning": "panjang", "audioText": "ちょう、なが" },
  { "character": "広", "romaji": "kou / hiro", "meaning": "luas", "audioText": "こう、ひろ" },
  { "character": "丸", "romaji": "gan / maru", "meaning": "bulat", "audioText": "がん、まる" },
  { "character": "交", "romaji": "kou / maji", "meaning": "bergiliran", "audioText": "こう、まじ" },
  { "character": "太", "romaji": "tai / futo", "meaning": "gemuk", "audioText": "たい、ふと" }
];

charactersData.kanji_n4 = realN4Kanji;

fs.writeFileSync(charactersFile, JSON.stringify(charactersData, null, 2));
console.log(`Successfully replaced kanji_n4 with ${realN4Kanji.length} authentic JLPT N4 kanji without placeholders.`);
